### ISSUE TITLE
Rebuild job fails with "Cannot transition status"

### ISSUE THREAD

**Issue by jangrewe** [gabrie-allaigre/sonar-gitlab-plugin#10]
When retrying a previous (successful) build of the same commit, the build fails with:

```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project peppr-capi: Failed to execute project builder: com.synaptix.sonar.plugins.gitlab.CommitProjectBuilder: Unable to update commit status: {"message":"Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via \"enqueue\")"}: Server returned HTTP response code: 400 for URL: https://gitlab.example.com/api/v3/projects/123/statuses/39c3977c -> [Help 1]
```

The scanner was started with:
```
mvn sonar:sonar -Dsonar.gitlab.project_id="myNameSpace/myProject" -Dsonar.gitlab.ref_name=${CI_BUILD_REF_NAME} -Dsonar.gitlab.commit_sha=${TAG} -Dsonar.analysis.mode=preview
```

It works perfectly fine on the first run for that commit, though!

**Comment by johnou** [comment]
According to https://docs.gitlab.com/ce/api/commits.html valid statuses are pending, running, success, failed, canceled

@gabrie-allaigre could we be sending the wrong status..?

```
Post the build status to a commit 

Adds or updates a build status of a commit.

POST /projects/:id/statuses/:sha

The state of the status. Can be one of the following: pending, running, success, failed, canceled
```

@jangrewe do you have multiple runners?

**Comment by johnou** [comment]
From the current source I see usages of pending, failed and success.

**Comment by gabrie-allaigre** [comment]
Hi,
In GitLab pipeline have you a current pending build with current commit ?
Because error is already exist pending for commit.

**Comment by johnou** [comment]
https://github.com/akrevenya/sonar-gitlab-plugin/commit/e7c165c2c12357ccec464dc57f3f853e780b06d0

"using running instead of pending due to this issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/25807"

@gabrie-allaigre looks like we just need to change the status here.
