### ISSUE TITLE
GitLab users in admin group

### ISSUE THREAD

**Issue by heruan** [gabrie-allaigre/sonar-gitlab-plugin#105]
I'm trying to assign a GitLab user to SQ `sonar-administrators` group, but when I log in with that user it is removed from the group. Is this expected? How can I make a GitLab account a SQ administrator?

**Comment by gabrie-allaigre** [comment]
Hi,
You use sonar-gitlab-auth- plugin ?

https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin

Thanks

**Comment by heruan** [comment]
Yes, plus I've just see the latest release fixes the issue. Thank you!
