### ISSUE TITLE
SonarQube failed to complete the review of this commit: No enum constant com.talanlabs.sonar.plugins.gitlab.models.QualityGate.Status.NONE

### ISSUE THREAD

**Issue by demeureguillaume** [gabrie-allaigre/sonar-gitlab-plugin#107]
Hello,

when using the latest version of this plugin, i've got this error : 
> SonarQube failed to complete the review of this commit: No enum constant com.talanlabs.sonar.plugins.gitlab.models.QualityGate.Status.NONE 

Environment : 
- SonarQube v6.3 (build 19869) using sonar-gitlab-plugin v3.0
- Jenkins 2.89.2 using Jenkinsfile
- Gitlab 10.0.1
- Maven Sonar Plugin 3.4.0.905 / 3.3.0.603

I remain at your disposal should you have any questions.

Guillaume Demeure

**Comment by gabrie-allaigre** [comment]
Hi,
What is a command line ?
Have you a complet log ?
Thanks

**Comment by gabrie-allaigre** [comment]
You use quality gate info ?
You have a quality gate status return NONE.
I will correct the problem

**Comment by demeureguillaume** [comment]
Sorry for the logs, i dont have it, but the command used with both version of maven plugin was : 

`mvn -Dsonar.branch.name=${GIT_BRANCH} -Dsonar.gitlab.commit_sha=${GIT_COMMIT} -Dsonar.gitlab.ref_name=${GIT_BRANCH} 
-Dsonar.host.url=${SONAR_URL}
-Dsonar.gitlab.ignore_certificate=true
-Dsonar.gitlab.project_id=${PROJECT_ID}
-Dsonar.gitlab.user_token=${GITLAB_USER_TOKEN}
-Dsonar.gitlab.all_issues=true -f app/pom.xml ${env.SONAR_MAVEN_GOAL}`

**Comment by gabrie-allaigre** [comment]
Hi,

Can you test with https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/download/3.0.1-rc1/sonar-gitlab-plugin-3.0.1-rc1.jar ?

Thanks

**Comment by demeureguillaume** [comment]
Hello, 

Thanks for the fix.

I guess it should solve the problem, i'll try to test today.

**Comment by gabrie-allaigre** [comment]
Ok, thanks

**Comment by demeureguillaume** [comment]
Hello Gabrie, 

i've found a workaround before your fix and i can't rollback projects to quality gate NONE (or i didn't found how).

I close the issue based on your fix, everything sounds good after reading the code.  

Thanks for your support.
