### ISSUE TITLE
Integration with GitLab CI

### ISSUE THREAD

**Issue by heruan** [gabrie-allaigre/sonar-gitlab-plugin#108]
In the README there are examples of how to integrate SQ with GitLab CI and they make use of secret variables `-Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN`. I suppose `SONAR_URL` is something like `http://localhost:9000/` or similar, but what about `SONAR_LOGIN`? How should I put in that variable?

**Comment by gabrie-allaigre** [comment]
Hi,

SONAR_LOGIN is a token in SonarQube, -> top/right -> My Account -> Security -> Create token

or use your login (SONAR_LOGIN) and password (SONAR_PASSWORD)

**Comment by heruan** [comment]
Thank you!
