### ISSUE TITLE
Link to show remaning extra issues on sonarqube server?

### ISSUE THREAD

**Issue by jakub-bochenski** [gabrie-allaigre/sonar-gitlab-plugin#111]
I think it would be nice to be able to show the issues not listed in the global comment on sonar in bulk.

![global](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/raw/master/doc/sonar_global.jpg)
E.g the text  `11. ... 67 more` could actually be a link to sonar's Issues list view. 

![screenshot_20180214_154833](https://user-images.githubusercontent.com/2794994/36210595-1c6ab4ca-119f-11e8-8aaf-0431a526d949.png)

The view supports filtering by source file so I think it's possible at this level. 
An open issue seems to be how to map file paths to sonar's `fileUuids`

**Comment by gabrie-allaigre** [comment]
Hi,
In preview mode, SonarQube not save issue. Change global template to show all issues.

https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/master/templates/global/all-issues.md

**Comment by jakub-bochenski** [comment]
OK, I've misunderstood how this feature works
