### ISSUE TITLE
Output isn't useful if more than one commit has been made since the last run

### ISSUE THREAD

**Issue by joineral32** [gabrie-allaigre/sonar-gitlab-plugin#12]
This tool works really well when there has only been one commit made on the branch per push. If I push up a single commit on my branch, it will make comments on that commit about the issues that were introduced.

However, if I am working on a branch and push up, say, 3 commits at once, it will only comment on offending lines in the last commit. It will comment a list of all of the issues added by all of the commits, but since it must run in preview mode "-Dsonar.analysis.mode=preview", I can't even go to Sonar to reference these issues.

**Comment by jairbubbles** [comment]
I have modified a little bit the code so it only list issues which correspond to lines modified by the current commit. I believe it might help you with your issue. I'll push it to GitHub and let you know.

**Comment by joineral32** [comment]
Well it would be ideal if we could get it to comment on all of the commits included on that branch since the last analysis.

**Comment by jairbubbles** [comment]
Ok I see. Your problem is different.
It's more a GitLab issue as only one pipeline is launched when you push 3 commits at the same time right ? I guess you can manually launch a pipeline on the intermerdiate commits and you'll get the comments inlined.

**Comment by johnou** [comment]
@jairbubbles would you kindly share your changes? I recently added SonarQube to an old project and there are hundreds of issues, I managed to prevent the plugin from reporting those every request by publishing the analysis of the project to SonarQube but it seems silly to do this every time we merge to master..

**Comment by johnou** [comment]
Removed my previous comment because I worked it out, I now only run sonar plugin in preview mode for feature branches and when those are merged into master run the publish mode which means the issue won't be reported again in the next merge request.

**Comment by jairbubbles** [comment]
@johnou  I'll make a merge request anyway ;-)

**Comment by johnou** [comment]
@jairbubbles after reading up further I am not sure changing it to list issues which correspond to lines modified by the current commit is a good idea, changing code in one area may cause issues in other areas of the codebase. gitlab.yml for my suggestion of running sonar in preview against feature branches and publish against master would look something like this..

```xml
sonarqube_preview:
  script:
    - mvn --batch-mode verify sonar:sonar -DskipITs -DskipTests -Dgpg.sign=false -Dsonar.host.url=https://xxx -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  except:
    - develop
    - master
    - /^hotfix_.*$/
    - /.*-hotfix$/
  tags:
    - java

sonarqube:
  script:
    - mvn --batch-mode verify sonar:sonar -DskipITs -DskipTests -Dgpg.sign=false -Dsonar.host.url=https://xxx -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  only:
    - master
  tags:
    - java
```

**Comment by jairbubbles** [comment]
@johnou First of all it's an option so you don't have to enable it. It really depends on what your workflow is.

In our case we only make full analysis on tags as we don't want to fill the SQ server with intermediate reports.

Secondly I had the issue when no report has been updated on the server yet. (We now force a full preview at first commit so it's less an issue.)

Finally, I don't really see the point of saying: "you have many other issues that is not related to your commit and that you can't even see on SQ as you're making a preview analysis".

**Comment by johnou** [comment]
@joineral32 multi-hash support was just added and is available in 2.0.0-beta2, sonar.gitlab.commit_sha can now be defined as follows..

```
mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/master..$CI_BUILD_REF | tr '\n' ',') -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.unique_issue_per_inline=true 
```

@gabrie-allaigre should be good to close this issue 👍

**Comment by jmiserez** [comment]
@johnou When I use the above options, I get the following error: (replaced the real domain with example.com):

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project tests: Failed to execute project builder: com.synaptix.sonar.plugins.gitlab.CommitProjectBuilder: Unable to perform GitLab WS operation: https://git.example.com/api/v3/projects/164/repository/commits/d5ff1697698b2d9e09f27cb4bbeff14a6b43d418,b79a3d6b4e46fe4c0fecc0b36f1b02ceca7a51fb,54fa93cbf7133455415b28e7419edb229e9f559c/diff -> [Help 1]`

Any ideas?

**Comment by gabrie-allaigre** [comment]
Hi,
Please use last version sonar-gitlab-plugin
Multi-commit is only last version

**Comment by jmiserez** [comment]
@gabrie-allaigre I see, just checked again and I was using 1.8.0. Thanks for the quick reply, I'll update.
