### ISSUE TITLE
Removing previous comments

### ISSUE THREAD

**Issue by lalib** [gabrie-allaigre/sonar-gitlab-plugin#134]
Hi, I have a question. After second build, I still see the previous sonar comments on Gitlab. 

Is there any way to remove the comments belong to old build and have new comments each time?

We use this feature in sonar-github plugin.

Best,

Bilal

**Comment by drown-zed** [comment]
I think there is a gitlab project setting under merge request "Automatically resolve merge request diff discussions when they become outdated", however never tested it with this plugin
