### ISSUE TITLE
Support with gitlab 11.0?

### ISSUE THREAD

**Issue by jasondamour** [gabrie-allaigre/sonar-gitlab-plugin#151]
Hello, I just upgraded to gitlab 11.0 and was greeted by this error in my CICD pipeline:
```
Execution failed for task ':sonarqube'.
> Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder

```
Is this a compatibility issue on the plugin side?

**Comment by jeanmorais** [comment]
I'm using GitLab CE 11.0.1 and it works fine

**Comment by osinglee** [comment]
I also met the same mistake

**Comment by gabrie-allaigre** [comment]
Hi verify if use v4 api

**Comment by jdamour98** [comment]
Thank you, I fixed it. I had version 2.1.0 which did not use v4 api. Upgrading to 3.0.0 resolved the issue.

**Comment by alixwar** [comment]
This issue should be closed
