### ISSUE TITLE
gitlab11.01+mysql issue

### ISSUE THREAD

**Issue by liao-bo** [gabrie-allaigre/sonar-gitlab-plugin#152]
i got  error message in gitlab production.log when i try to run scan command in gitlab-ci
error message:

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xF0\x9F\x9A\xAB</...' for column 'note_html' at row 1: INSERT INTO `notes` (`note`, `noteable_type`, `commit_id`, `project_id`, `author_id`, `discussion_id`, `created_at`, `updated_at`, `note_html`, `cached_markdown_version`, `system`) VALUES ('SonarQube analysis reported 23 issues\n* :no_entry_sign: 4 critical\n* :warning: 12 major\n* :arrow_down_small: 7 minor\n\n#### Top 10 extra issues\n\nNote: The following issues were found on lines that were not modified in the commit. Because these issues can\'t be reported as line comments, they are summarized here:\n\n1. :no_entry_sign: [Refactor this function to reduce its Cognitive Complexity from 23 to the 15 allowed.](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/main.go#L153) [:blue_book:](https://sonarqube.hexcloud.cn/coding_rules#rule_key=go%3AS3776)\n1. :no_entry_sign: [Refactor this function to reduce its Cognitive Complexity from 17 to the 15 allowed.](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/routes/websocket.go#L40) [:blue_book:](https://sonarqube.hexcloud.cn/coding_rules#rule_key=go%3AS3776)\n1. :no_entry_sign: [Refactor this function to reduce its Cognitive Complexity from 16 to the 15 allowed.](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/routes/websocket.go#L135) [:blue_book:](https://sonarqube.hexcloud.cn/coding_rules#rule_key=go%3AS3776)\n1. :no_entry_sign: [Refactor this function to reduce its Cognitive Complexity from 72 to the 15 allowed.](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/service/auth.go#L60) [:blue_book:](https://sonarqube.hexcloud.cn/coding_rules#rule_key=go%3AS3776)\n1. :warning: [Was \"+=\" meant instead?](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/main.go#L52) [:blue_book:](https://sonarqube.hexcloud.cn/coding_rules#rule_key=go%3AS2757)\n1. :warning: [Remove this commented out code.](https://gitlab.hexcloud.cn/bo.liao/hipos-gateway/blob/014559f639d591fa856886b45769b46a5588b122/vendor/github.com/ugorji/go/codec/test.py#L70) [:blue_book:]

The sonar scanner command : #sonar-scanner -X -Dsonar.host.url="https://sonarqube.hexcloud.cn"  -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID'

**Comment by TobiX** [comment]
Looks like an unicode issue on the MySQL side, is your MySQL installation correct? https://docs.gitlab.com/ee/install/database_mysql.html#mysql-utf8mb4-support seems like a probable culprit. It seems GitLab does not recommend using MySQL with GitLab...
