### ISSUE TITLE
can't find codeclimat.json

### ISSUE THREAD

**Issue by iluwaa** [gabrie-allaigre/sonar-gitlab-plugin#156]
runnig scanner localy with "/d:sonar.gitlab.json_mode=CODECLIMAT". But codeclimat.json wasn't created, how to fix it?

**Comment by gabrie-allaigre** [comment]
Hi,
what is full command line ?

**Comment by iluwaa** [comment]
`- dotnet sonarscanner begin  /k:Uklon.Notification1 /d:sonar.analysis.mode=preview /d:sonar.gitlab.project_id=%CI_PROJECT_PATH% /d:sonar.key=912e8103f0f563f6089200c807c22b3113777ae9 /d:sonar.gitlab.commit_sha=%CI_COMMIT_SHA% /d:sonar.gitlab.ref_name=%CI_COMMIT_REF_NAME% /d:sonar.gitlab.json_mode=CODECLIMATE /d:sonar.gitlab.failure_notification_mode=commit-status`

**Comment by gabrie-allaigre** [comment]
Version plugin ? and log please
Thanks

**Comment by iluwaa** [comment]
2.1.0
[sonar-runner.log](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/2219422/sonar-runner.log)
[analysis.log](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/2219423/analysis.log)

**Comment by iluwaa** [comment]
solved(updated plugin). Thanks.
