### ISSUE TITLE
Unable to use global setting for Gitlab user token

### ISSUE THREAD

**Issue by Andrew-Stubbs** [gabrie-allaigre/sonar-gitlab-plugin#159]
This seems to be the same issue experienced by @vuza in this closed issue: https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/89#issuecomment-385245321

I have added a *GitLab User Token* within
> General Settings -> GitLab
in SonarQube, that was generated from an admin account within GitLab.

When I run my jobs from GitLab with the following command:
> mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

I see the following error message:
>[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project cars-service: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder: Unable found project for highways-england/c
ars-service Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 1]

However when I use this command (Specifying the same user token as I already added to the SonarQube settings):
> mvn compile sonar:sonar  -Dsonar.gitlab.user_token=$GITLAB_TOKEN -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

The project builds and receives comments from SonarQube as expected.

Why does the global setting not seem to be being applied (I am using plugin v3.0.1)?

Thanks.

**Comment by gabrie-allaigre** [comment]
Hi,
Are you sur for :

```
mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
```
Because error message say : Unable found project for **highways-england/cars-service**

$CI_PROJECT_ID=highways-england/cars-service ? It's impossible, gitlab get a number

**Comment by Andrew-Stubbs** [comment]
Sorry @gabrie-allaigre , you are correct, I have been playing with calling the integration locally as well as via gitlab while trying to diagnose the problem.

Two outputs directly from GitLab:
Failing:
> $ mvn compile sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

>20501 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.1.1168:sonar (default-cli) on project cars-service: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder: Unable found project for 184 Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 1]


Succeeding:
>$ mvn compile sonar:sonar  -Dsonar.gitlab.user_token=$GITLAB_TOKEN -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

**Comment by gabrie-allaigre** [comment]
Ok thanks,

Are you sur save  2 times user_token in admin. There was a bug in sonar 7.0 with password fields

https://groups.google.com/forum/#!searchin/sonarqube/gabriel$20%7Csort:date/sonarqube/h5lvM4Iwll8/eG6RV1h1AQAJ

**Comment by Andrew-Stubbs** [comment]
You're a lifesaver, thanks @gabrie-allaigre 

The problem does seem to be that I never actually saved the *Gitlab User Token*, despite it looking like I had.

Apologies for wasting your time with user error!
