### ISSUE TITLE
Only scan commited files

### ISSUE THREAD

**Issue by suanziliu** [gabrie-allaigre/sonar-gitlab-plugin#171]
I'm using gitlab-ci pipeline, it will run a new docker container with following commands:
`mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.only_issue_from_commit_file=true -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.host.url=xxx -Dsonar.test.inclusions="/src/test/java/**/*.java" -Dsonar.login=xxx`

It becomes quite slow for my project, almost run for 20mins. 
I found that seems like it will scan all files instead of only the commited files.

Is there anything wrong with my configurations?

**Comment by gabrie-allaigre** [comment]
Hi,
SonarQubeScanner scan all files, but Sonar-Gitlab-Plugin will only comment on commit files
Have you a log ?

**Comment by suanziliu** [comment]
@gabrie-allaigre Thanks for your reply. Sorry that I it is my own problem about it. I will close this issue.
