### ISSUE TITLE
How to fail GitLab CI Job if sonar scanner find a major issue?

### ISSUE THREAD

**Issue by pedroIsai21** [gabrie-allaigre/sonar-gitlab-plugin#174]
I am trying to fail a gitlab ci job if there are major issues.
I'm not sure if the sonar.gitlab.max_major_issues_gate should work for this purpose.

Regards.

**Comment by gabrie-allaigre** [comment]
Hi, yes set value with 0

**Comment by pedroIsai21** [comment]
> Hi, yes set value with 0

Thanks, Works fine.

**Comment by Nymeria333** [comment]
@gabrie-allaigre Please help!!!
I need the GitLab pipeline job to fail if it finds atleast 1 major issue.
But everytime the Job succeeds.
![GlSexecution](https://user-images.githubusercontent.com/23304265/57435500-31868280-725b-11e9-81ba-11d114484446.PNG)

This is my .gitlab-ci.yml 

stages:
- code_quality
variables:
  SONAR_LOGIN: "xyz"
  SONAR_PASSWORD: "xyz"
  SOURCE: "."
  

sonarqube_master_job:
  stage: code_quality
  tags:
    - docker
  only:
    - development

  script:
    - cd ..
    - sonar-scanner/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD -Dsonar.sources=$SOURCE -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.failure_notification_mode=exit-code

**Comment by gabrie-allaigre** [comment]
@Nymeria333 Hi, please open a new issue.
By default, major, no fail. Set attribute -Dsonar.gitlab.max_major_issues_gate=0 to fail with major

**Comment by spsankpal** [comment]
is there a project example for failing this for major issue>0.
Its not working for me, installed the attached plugin for 5.7 version.
the sonar analysis is success for quality fate pass/ fail, and exceutes the deploy stage all the cases
