### ISSUE TITLE
No codeclimate.json generated for GitLab Starter

### ISSUE THREAD

**Issue by jacobk** [gabrie-allaigre/sonar-gitlab-plugin#180]
Plugin version: 4.0

Is the codeclimate.json generation supposed to work with GitLab Starter? https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html

No codeclimate.json file is generated when I run:
```
/gradlew --stacktrace sonarqube -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$SHA -Dsonar.gitlab.ref_name=$BRANCH -Dsonar.gitlab.project_id=$PROJ -Dsonar.gitlab.json_mode=CODECLIMATE
```

**Comment by gabrie-allaigre** [comment]
Hi,
Have you full log ?
Thanks

**Comment by jacobk** [comment]
Hello, 
Thanks, which log, Should I run gradle with `-d` is that enough?

**Comment by gabrie-allaigre** [comment]
yes

**Comment by jacobk** [comment]
Ok, here it is:

[sonarbuild.log](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/2437008/sonar.log)

**Comment by jacobk** [comment]
However it's empty. I have a comment like this from the plugin:
![image](https://user-images.githubusercontent.com/497477/46346018-e8c47680-c646-11e8-92c9-8a8e21bced87.png)

If I run the command line above with that SHA and branch name I was expecting the same errors to be present in the codeclimate.json (it's simply `[]`). But maybe this assumption is wrong?

**Comment by jacobk** [comment]
My bad again. Was running on the wrong branch locally. Works as intended!

**Comment by gabrie-allaigre** [comment]
Good
