### ISSUE TITLE
Cannot resolve the com.synaptix:java-gitlab-api:jar:1.4.0 dependency

### ISSUE THREAD

**Issue by xnslong** [gabrie-allaigre/sonar-gitlab-plugin#2]
I can compile it now. It failed to resolve the dependency may because my sonartype nexus failed to fetch the dependency from the Central repository. It compiled successfully when I removed the settings.xml and downloaded dependencies directly from the Central repository.

> Hi,
> 
> I cloned the project and tried to compile it with the `mvn compile` command, but I got an ERROR that the following dependency cannot be resolved.
> 
> ``` xml
>  <dependency>
>             <groupId>com.synaptix</groupId>
>             <artifactId>java-gitlab-api</artifactId>
>             <version>${java-gitlab-api.version}</version>
> </dependency>
> ```
> 
> where can I find it?

**Comment by gabrie-allaigre** [comment]
Hi
I use repository in pom.xml
```xml
<repositories>
        <repository>
            <id>talanlabs-releases-repository</id>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
            <url>http://nexus.talanlabs.com/content/groups/public_release</url>
        </repository>
        <repository>
            <id>talanlabs-snapshots-repository</id>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <url>http://nexus.talanlabs.com/content/groups/public_snapshots</url>
        </repository>
    </repositories>
```
Do you use Mirror or proxy ?

**Comment by johnou** [comment]
@gabrie-allaigre it might be worth publishing to central so building the project does not rely on talanlabs?

**Comment by gabrie-allaigre** [comment]
My java-gitlab-api is in Maven Central now.

**Comment by johnou** [comment]
@gabrie-allaigre why 1.0.0? is this it? http://search.maven.org/#artifactdetails%7Ccom.talanlabs%7Cjava-gitlab-api%7C1.0.0%7Cjar , looks like https://github.com/gabrie-allaigre/java-gitlab-api hasn't been updated, was the release done from another repository?

**Comment by gabrie-allaigre** [comment]
It's same api but with rebase, change domaine and deploy in maven central.
I update repository  https://github.com/gabrie-allaigre/java-gitlab-api
