### ISSUE TITLE
Can support multiple gitlab addresses

### ISSUE THREAD

**Issue by shouldnotappearcalm** [gabrie-allaigre/sonar-gitlab-plugin#235]
I have multiple gitlab addresses here, I want to configure it in sonar, but it seems that I can only configure one. Can I configure multiple gitlab addresses? Is it separated by commas?

**Comment by gentunian** [comment]
+1

I just recently discovered this. You read my mind and beat me by 6 hours! :)

**Comment by gabrie-allaigre** [comment]
Hi,
Each project, you set attribute -Dsonar.gitlab.url=gitlab.com

**Comment by shouldnotappearcalm** [comment]
> Hi,
> Each project, you set attribute -Dsonar.gitlab.url=gitlab.com

Ok, I will try it, thank you very much.
