### ISSUE TITLE
‘GitLab Commit Issue Publisher’ skipped because one of the required properties is missing

### ISSUE THREAD

**Issue by ghost** [gabrie-allaigre/sonar-gitlab-plugin#244]
Sonarqube 6.7 with sonar-scanner and Gitlab-plugin 3.0.2

Sonar-project.properties file:

sonar.projectKey=<project_key>
sonar.projectName=<project_name>

sonar.analysis.mode=preview

sonar.sources=<sources_folder>

sonar.sourceEncoding=UTF-8

sonar.language=c

sonar.cfamily.build-wrapper-output=<folder_name>

sonar.branch.name=<branch_name>
sonar.gitlab.commit_sha=<commit_sha>
sonar.gitlab.project_id=<project_id>
sonar.gitlab.url=<gitlab_url>
sonar.gitlab.user_token=<user_token>

Build is successful. But I see the below line in the log and I see no inline comments in gitlab.

DEBUG: ‘GitLab Commit Issue Publisher’ skipped because one of the required properties is missing

And also a new job is created in the end and it says Sonarqube analysis in progress and the job status is pending and it never starts.

**Comment by edcu11** [comment]
Were you able to find a solution?

**Comment by ghost** [comment]
not yet.

**Comment by lanniu** [comment]
try this "sonar-scanner -X -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME"

**Comment by ghost** [comment]
Thanks Lanniu. 
This command worked for me:
sonar-scanner -X -Dsonar.analysis.mode=publish -Dsonar.host.url=<Host_URL> -Dsonar.login=<user_id> -Dsonar.password=${password} -Dsonar.gitlab.url=<gitlab_url> -Dsonar.gitlab.commit_sha=${COMMIT_SHA} -Dsonar.gitlab.project_id=${PROJECT_ID} -Dsonar.gitlab.ref_name=${BRANCH_NAME}
