### ISSUE TITLE
Fix examples

### ISSUE THREAD

**Issue by tholu** [gabrie-allaigre/sonar-gitlab-plugin#27]
Only one of this should work:

`-Dsonar.gitlab.project_id=$CI_PROJECT_ID`
`-Dsonar.gitlab.project_id=$CI_PROJECT_PATH`

Both variants are used in the README.

Also check if Gitlab 9.0 changed things: https://docs.gitlab.com/ce/ci/variables/#9-0-renaming

**Comment by gabrie-allaigre** [comment]
Hi,
sonar.gitlab.project_id accept id or internal id or namespace + name or namespace + path or url http or ssh url or url or web

- CI_PROJECT_ID return project id
- CI_PROJECT_PATH return namespace+path

Yes, I need to change the CI_BUILD_REF and CI_BUILD_REF_NAME in the readme thank.
