### ISSUE TITLE
The API is not support more than one commit-sha

### ISSUE THREAD

**Issue by yileye** [gabrie-allaigre/sonar-gitlab-plugin#28]
Hi
I install sonar-gitlab-plugin in my server.The version is 5.6. The plugin is 1.7 maybe.

If I post a merge request in gitlab, I want to plugin help me post sonar info in merge request.

I have some problems：

1.I run the command in shell:
mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

2.I get more than one sonar.gitlab.commit_sha value, and the error info is '{"message":"404 Commit Not Found"}'
the url is 'http://gitlab.xx.cn/api/v3/projects/3/repository/commits/8c4aa70d9d897ebfe3680bb8becdffad0471019b,0f4aa70d9d897ebfe3680bb8becdffad04710192/diff'
3.According to the official document ，doesn't support this kind of request，only support single commit_sha.

Should I worry about this problem? I was blocking in this case！

**Comment by johnou** [comment]
@yileye please try the latest version of the plugin 2.0.1 which is available from the update center.

**Comment by johnou** [comment]
please also verify you are using the correct variable naming..

| GitLab 8.x name | GitLab 9.x name |
| -------- | ----------- |
| CI_BUILD_REF | CI_COMMIT_SHA |
| CI_BUILD_REF_NAME | CI_COMMIT_REF_NAME |

https://docs.gitlab.com/ce/ci/variables/#9-0-renaming

**Comment by gabrie-allaigre** [comment]
Hi,
CI_BUILD_REF  is only for gitlab-ci.
For Jenkins please show
https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin on environnement
variable.

**Comment by yileye** [comment]
@johnou I try the command with new parameter
like this:
`mvn --batch-mode verify sonar:sonar -Dmaven.test.skip=true  -Dsonar.host.url=http://sonar.xx.cn:9000 -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$(git log --pretty=format:%H origin/develop..$CI_COMMIT_SHA | tr '\n' ',') -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=bis/bi-cel -Dsonar.gitlab.unique_issue_per_inline=true`

The resault is :
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project bi-cel: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor: Unable to perform GitLab WS operation: http://gitlab.xx.cn/api/v3/projects/308/repository/commits/8c4aa70d9d897ebfe3680bb8becdffad0471019b,c2c8b16af63fcf2e2b68aca3430089105f1b0c96,9a31aa193c920c30acdfe6328e0caa3a96010c14,641252bcc5ad9bb64dfdb300c016f7d8d16c8dae,f6db68349564605cf0db123ea7bf426164d08d24,5ede7918c3cc2ddbe8b10b835cb68badfddb81e5,040735b3c44510ac51d0d55b19f02b3023f2ea30,87d7d3f3a00dee52e9432b74d7b25f2307c86c1f/diff`

I think the error is the api is not support more than one CI_COMMIT_SHA, one CI_COMMIT_SHA can post success, like this:

`http://gitlab.xx.cn/api/v3/projects/308/repository/commits/87d7d3f3a00dee52e9432b74d7b25f2307c86c1f/diff`

`// 20170410173939
// http://gitlab.xx.cn/api/v3/projects/308/repository/commits/87d7d3f3a00dee52e9432b74d7b25f2307c86c1f/diff

[
  {
    "diff": "--- a/src/main/java/com/puhui/bi/cel/dao/MybatisDao.java\n+++ b/src/main/java/com/xx/xx/xx/dao/MybatisDao.java\n@@ -24,6 +24,10 @@ public class MybatisDao {\n     }\n \n     public <E> List<E> selectList(String namespace,Object object){\n+        //k\n+        //l\n+        //l\n+        //l\n         return sqlSessionTemplate.selectList(namespace,object);\n     }\n \n",
    "new_path": "src/main/java/com/xx/xx/xx/dao/MybatisDao.java",
    "old_path": "src/main/java/com/xx/xx/xx/dao/MybatisDao.java",
    "a_mode": "100644",
    "b_mode": "100644",
    "new_file": false,
    "renamed_file": false,
    "deleted_file": false,
    "too_large": null
  }
]`

I will try gitlab-ci . Thank you！

**Comment by gabrie-allaigre** [comment]
Multi hash id available only with 2.0.1 version.
Thanks.

**Comment by yileye** [comment]
Thank you for you help !

It can work now, the effect is really amazing.

Thank you for your contribution.

I only need to update version to 2.0 now .

**Comment by yileye** [comment]
Please close this issue
