### ISSUE TITLE
sonar.gitlab.only_issue_from_commit_file does not seem to work

### ISSUE THREAD

**Issue by jairbubbles** [gabrie-allaigre/sonar-gitlab-plugin#30]
... or i don't understand what it's supposed to do.

I want my analysis to only report issues which are inlined. Even after setting this to true I get extra issues:
![image](https://cloud.githubusercontent.com/assets/15875066/24911929/9b2f3eaa-1e9a-11e7-8ca5-da616bd8d802.png)

Here is my command line:
![image](https://cloud.githubusercontent.com/assets/15875066/24912019/de0a956c-1e9a-11e7-987a-57aa11312c2f.png)

**Comment by gabrie-allaigre** [comment]
Can you give me the command line you make ?
Thanks.

**Comment by jairbubbles** [comment]
@gabrie-allaigre Is the screenshot of my commmand line not enough?

**Comment by gabrie-allaigre** [comment]
Sorry in email, I don't see capture.
I see on github.

**Comment by jairbubbles** [comment]
Here you go:
```
C:\Users\svc_toolsquarerobot\AppData\Local\Temp\TeaBoxTools\MSBuild.SonarQube.Runner-2.2\MSBuild.SonarQube.Runner.exe begin /d:sonar.host.url="http://sonarqube" /k:"GhostReconTools:Feedback" /n:"Feedback" /v:"1.0.0" /d:sonar.cs.nunit.reportsPaths=NUnitResults.xml /d:sonar.cs.xunit.reportsPaths=XUnitResults.xml /d:sonar.cs.vstest.reportsPaths=MSTestResults.trx /d:sonar.cs.dotcover.reportsPaths=coverageReport.html /d:sonar.gitlab.url=https://gitlab-ncsa.ubisoft.org /d:sonar.gitlab.user_token=vpNCZx1nqDyGN1gjoqex /d:sonar.gitlab.project_id=5255 /d:sonar.gitlab.commit_sha=1ac7b7e2e308ab67506e1da4ec1872bcd2755c66 /d:sonar.gitlab.ref_name=coreimplementation /d:sonar.issuesReport.console.enable=true /d:sonar.analysis.mode=preview /d:sonar.gitlab.only_issue_from_commit_file=true
```

**Comment by gabrie-allaigre** [comment]
Ok it's a bug.
I fix the next week.

**Comment by jairbubbles** [comment]
Thanks,

As a side note I feel like a s to the option name would more correct: `issue_from_commit_fileS`  
(I've added a similar option in a fork called `only_inlined_issues` if I remember correctly.)

**Comment by gabrie-allaigre** [comment]
Hi,
`only_issue_from_commit_file` add issue only for commit file

Example:

project with 2 files Foo1.php & Foo2.php
Modify (line 1) & commit only Foo1.php

Plugin report only all issues for Foo1.php (line 1 AND others lines issues).

I can add an option that allows to have in the global comment that the inline issues ?

**Comment by jairbubbles** [comment]
Ok, so it seems to be almost what I expect. If you commit 2 files you'll only have issues from those files right ?
  
If I understand correctly my option `online_inline_issues` is a little bit different as the plugin is reporting only issues that corresponds to commits lines.

It might explain why I was still getting extra issues in the summary report.

**Comment by jairbubbles** [comment]
@gabrie-allaigre Do you think you can add `only_inline_issues` option anytime soon? Always having "extra issues" on our workflows is quite an issue as it generates a lot of noise and builds are marked as failed while they should not.  
*If you need more info on what exactly are our current workflows, I'd be delighted to!*

**Comment by gabrie-allaigre** [comment]
It's done but not finish at test
Here https://github.com/gabrie-allaigre/sonar-gitlab-plugin/tree/commit_line

`sonar.gitlab.only_issue_from_commit_line=true`

**Comment by jairbubbles** [comment]
Awesome! Will you publish directly to update center?

**Comment by gabrie-allaigre** [comment]
I add another requested that I was made and I do the release

**Comment by gabrie-allaigre** [comment]
If it's really urgent, you can use the global template. Display only inline with:

```
<#assign newIssueCount = issueCount(true)>
<#if newIssueCount == 0>
SonarQube analysis reported no issues.
<#else>
SonarQube analysis reported ${newIssueCount} issue<#if newIssueCount gt 1>s</#if>
    <#assign newIssuesBlocker = issueCount(true,BLOCKER) newIssuesCritical = issueCount(true,CRITICAL) newIssuesMajor = issueCount(true,MAJOR) newIssuesMinor = issueCount(true,MINOR) newIssuesInfo = issueCount(true,INFO)>
    <#if newIssuesBlocker gt 0>
* ${emojiSeverity(BLOCKER)} ${newIssuesBlocker} blocker
    </#if>
    <#if newIssuesCritical gt 0>
* ${emojiSeverity(CRITICAL)} ${newIssuesCritical} critical
    </#if>
    <#if newIssuesMajor gt 0>
* ${emojiSeverity(MAJOR)} ${newIssuesMajor} major
    </#if>
    <#if newIssuesMinor gt 0>
* ${emojiSeverity(MINOR)} ${newIssuesMinor} minor
    </#if>
    <#if newIssuesInfo gt 0>
* ${emojiSeverity(INFO)} ${newIssuesInfo} info
    </#if>

Watch the comments in this conversation to review them.
</#if>
```

**Comment by jairbubbles** [comment]
@gabrie-allaigre Indeed, template system seems very powerful.

Where in the given example do you diplay only inline ?

**Comment by gabrie-allaigre** [comment]
In `issueCount(true)` `true` param get only issues reported inline.

**Comment by jairbubbles** [comment]
@gabrie-allaigre Any ETA on the new version?

**Comment by gabrie-allaigre** [comment]
Hi,
New alpha version https://github.com/gabrie-allaigre/sonar-gitlab-plugin/releases/tag/2.1.0-alpha.1
Add option -Dsonar.gitlab.only_issue_from_commit_line=true

**Comment by jairbubbles** [comment]
Thx! Testing right away.

**Comment by jairbubbles** [comment]
So far so good.
 I just added in my commit:
![image](https://cloud.githubusercontent.com/assets/15875066/26160339/4a63d032-3b21-11e7-994a-6eb0dcd6b2ed.png)
And I only have a comment on this line:
![image](https://cloud.githubusercontent.com/assets/15875066/26160390/6baecd5a-3b21-11e7-8c52-8d728c3faa14.png)

Thx again!
