### ISSUE TITLE
Sonarcube permission error while trying to do the analysis

### ISSUE THREAD

**Issue by geetika95** [gabrie-allaigre/sonar-gitlab-plugin#31]
Hello Folks,

I am trying to use this plugin and facing one issue or the other. I am using Sonar version 6.2 and Gitlab version 9.0.4. 

I am using below command in the .yml file.

    `- mvn -X sonar:sonar -Dgpg.sign=false -Dsonar.host.url=<Sonar Server URL> -Dsonar.login=<sonar-user-name> -Dsonar.password=<sonar-password> -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME`

**Issue 1:** If I don't specify the sonar username and password I get the permission error
**_"Caused by: You don't have the required permissions to access this project. Please contact your SonarQube administrator."_**
I have the user token correctly setup in the sonar server. Even after specifying the same in the command line, I still get the same error.

**Issue 2:** I am not able to get the issues being added in Gitlab UI/commits. Using the above command is resulting into the below error message:

_**"Caused by: java.io.FileNotFoundException: https://<GITLAB-HOST_NAME>/api/v3/projects/191/repository/commits/$CI_COMMIT_SHA/comments
"**_

I have been struggling with this issue for so many days. Please suggest what am I doing wrong.

**Comment by jairbubbles** [comment]
I think you should use `sonar.gitlab.user_token=<user_token>` with a user token created on your GitLab server.

**Comment by gabrie-allaigre** [comment]
Hi,

Issue 1 : 
In SonarQube your project must be accessible to the user. With token, no fill password.

Issue 2 : 
What is gitlab-runner version ?

**Comment by geetika95** [comment]
Hi @jairbubbles and @gabrie-allaigre ,

Thanks for replying. My updates:

Issue 1: How to ensure that the project is accessible to the user with token? I tried with the two tokens. 
1. Generated on gitlab server and I copied it over to sonar cube administration console and user the same in the command, but no luck. 
2. I created a new user  in sonarcube and got a token for that user. I used this token in my command line as well as in the administration settings (for gitllab) in Sonarcube. 

Also, I don't see a user token property in the project settings of sonarcube.

I am confused now, This `sonar.gitlab.user_token` is refering to which one, the Gitlab created on Gitlab or the one created on sonarcube?

Issue 2: I used the steps specified one below page 

https://docs.gitlab.com/runner/install/windows.html

and used the latest binary. I think it is **9.0.1**

**Comment by gabrie-allaigre** [comment]
Hi,
If gitlab-runner run on Windows then variable environement format is `%CI_COMMIT_SHA%`

**Comment by gabrie-allaigre** [comment]
It takes 2 users
- one from Gitlab who has access to the source of the project on Gitlab and must be at least a developer. `sonar.gitlab.user_token`
- one from Sonarqube who has access to the project in SonarQube `sonar.login`

**Comment by geetika95** [comment]
This works. Thanks a ton @gabrie-allaigre. :) 

I can see the comments getting added to the commits. Can you also let me know if it is possible to add these comments on the changes of an MR?

**Comment by gabrie-allaigre** [comment]
GitLab does not allow to do on the MR (API not exist)
