### ISSUE TITLE
Wrong issue severity

### ISSUE THREAD

**Issue by aaitmouloud** [gabrie-allaigre/sonar-gitlab-plugin#38]
Hello,

I'm executing the `sonar-gitlab-plugin` (from Jenkins Pipeline using withSonarQubeEnv from Jenkins Sonarqube Plugin)

```
withSonarQubeEnv('My SonarQube 6.2') {
    sh "mvn -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$GIT_COMMIT -Dsonar.gitlab.ref_name=$BRANCH_NAME -Dsonar.gitlab.project_id=$PROJECT_ID org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar"
}
```
Everything is fine, i have the comments on GitLab, except for one thing.

The severity of the issues commented by the `sonar-gitlab-plugin` is not the same as the severity of the issue on my SonarQube server (version 6.2).

Here is an example of a comment i have on one of my commits (i have the correct URL to my server in "`LINKTOMYSONAR62SERVER`")
> ![MAJOR](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/raw/master/images/severity-major.png) Remove this usage of alert(...). [![RULE](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/raw/master/images/rule.png)](http://LINKTOMYSONAR62SERVER/coding_rules#rule_key=javascript%3AS1442)

And when i click on the three dots, i have this
![2017-05-17_17h05_31](https://cloud.githubusercontent.com/assets/10416773/26161038/0d3dd84a-3b23-11e7-9719-8716ad4ebd9f.png)

Thank you.

**Comment by gabrie-allaigre** [comment]
Hi,
What are you quality profile ?
Per default, issue is major :
![image](https://cloud.githubusercontent.com/assets/14994297/26161258/b943d95a-3b23-11e7-996b-06e6887db552.png)

**Comment by aaitmouloud** [comment]
It's a custom Quality profile based of Sonar way

**Comment by gabrie-allaigre** [comment]
In Sonar way profile, issue is major.

**Comment by aaitmouloud** [comment]
Isn't the plugin supposed to be based on the rules of the server not of the default one?

**Comment by gabrie-allaigre** [comment]
Yes, plugin use based rules of server.
Sonar makes it possible to change the severity by profile.
Verify if your profile use default severity ?
Same here :
![image](https://cloud.githubusercontent.com/assets/14994297/26174537/ff43e216-3b4f-11e7-8833-df3b47231ad4.png)

And verify if project use custom quality profile.

**Comment by gabrie-allaigre** [comment]
@aaitmouloud What was the problem ?

**Comment by aaitmouloud** [comment]
It seems that the Sonarqube database was corrupt by migration from version 5.5

**Comment by gabrie-allaigre** [comment]
The plugin does not touch the base of SonarQube
