### ISSUE TITLE
Use the plugin on freestyle projects

### ISSUE THREAD

**Issue by ZoeThivet** [gabrie-allaigre/sonar-gitlab-plugin#43]
Hello, I'm having trouble to  configure your plugin because I'm trying to run it on a non-gradle and non-mvn project. It's just a simple freestyle project. Is there a sample command to achieve this? Thank you.

I'm using Jenkins, and I created a Jenkins freestyle job with a "Launch a SonarQube Scanner analysis" and this config:

```
sonar.projectKey=stuff
sonar.projectName=stuff
sonar.projectVersion=5.6.4
sonar.sources=.
sonar.analysis.mode=preview
sonar.gitlab.commit_sha=${CI_BUILD_REF}
sonar.gitlab.ref_name=${CI_BUILD_REF_NAME}
sonar.gitlab.project_id=${CI_PROJECT_ID}
sonar.issuesReport.console.enable=true
```

I'm getting this error:

`Caused by: java.lang.IllegalStateException: Unable found project for ${CI_PROJECT_ID} Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project`

**Comment by ZoeThivet** [comment]
PS: I found a dirty workaround to fix the problem. Please keep me informed if I'm missing something.

SHA_LAST_COMMIT=$(git rev-parse origin/master)
echo $SHA_LAST_COMMIT
sed -i "s/\${CI_BUILD_REF}/$SHA_LAST_COMMIT/g" sonar-project.properties
sed -i "s/\${CI_BUILD_REF_NAME}/$SHA_LAST_COMMIT/g" sonar-project.properties

**Comment by gabrie-allaigre** [comment]
Hi, ${CI_BUILD_REF} and ${CI_BUILD_REF_NAME} is only GitLab-CI
For Jenkins, https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin
Environment variables : 
- GIT_COMMIT - SHA of the current
- GIT_BRANCH - Name of the remote repository (defaults to origin), followed by name of the branch currently being used, e.g. "origin/master" or "origin/foo"
- GIT_LOCAL_BRANCH - Name of the branch on Jenkins. When the "checkout to specific local branch" behavior is configured, the variable is published.  If the behavior is configured as null or **, the property will contain the resulting local branch name sans the remote name.

**Comment by gabrie-allaigre** [comment]
Same ${CI_PROJECT_ID} is only GitLab-CI
Set namespace + project or set project id (go to gitlab project settings and copy project id)

**Comment by ZoeThivet** [comment]
Wow, it now sounds obvious :) thank you very much for your quick answer, way better than my messy workaround.
