### ISSUE TITLE
Comment inline in all commits of branch not working

### ISSUE THREAD

**Issue by gerbsen** [gabrie-allaigre/sonar-gitlab-plugin#48]
Hey there,
I'm trying to use this plugin, but the inline comments do not work for this project. 

I've configured a GitLab User in Sonarcube with an access token, its part of the java group that is able to do everything. The project url and id (numeric?) is set in the configuration. The normal `- mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN` works perfectly.

```
- mvn --batch-mode -X verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
```
Fails with the following error message :(

```
Caused by: java.lang.IllegalStateException: Unable found project for api-server/r360-service Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.getGitLabProject(CommitFacade.java:144)
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.init(CommitFacade.java:80)
```

any idea?

**Comment by gabrie-allaigre** [comment]
Hi,
Gitlab User token access to project ?

**Comment by gerbsen** [comment]
I'm so stupid... It was Friday.. Thanks for the help and the plugin !
