### ISSUE TITLE
All issues instead of new ones?

### ISSUE THREAD

**Issue by AlexSchuetz** [gabrie-allaigre/sonar-gitlab-plugin#49]
How to write a template to report all issues and not only new ones?

**Comment by gabrie-allaigre** [comment]
Hi,
Plugin get only new issue.
I need to make a change in the code

**Comment by AlexSchuetz** [comment]
I found a workaround:

If I use "-Dsonar.branch=dummy" (this branch doesn't exit in sonarqube) all issues will be new issues, since there is no previous analyses.

**Comment by gabrie-allaigre** [comment]
I think sonar.branch is deprecated

**Comment by AlexSchuetz** [comment]
Taking new issues compared to main branch now. This works fine.
