### ISSUE TITLE
Comment images won't show because href is on gitlab.talanlabs.com

### ISSUE THREAD

**Issue by clorichel** [gabrie-allaigre/sonar-gitlab-plugin#5]
Images in the comments won't show because they link to your gitlab domain, as example : https://gitlab.talanlabs.com/gabriel-allaigre/sonar-gitlab-plugin/raw/master/images/severity-major.png

This happen wether inline comments :
<img width="263" alt="capture d ecran 2016-08-23 a 08 43 05" src="https://cloud.githubusercontent.com/assets/12629433/17892125/beace83e-690d-11e6-817d-c18c2079a96b.png">

Or global comments :
<img width="366" alt="capture d ecran 2016-08-23 a 08 43 13" src="https://cloud.githubusercontent.com/assets/12629433/17892124/bea7c444-690d-11e6-8998-ade8a03b511a.png">

**Comment by gabrie-allaigre** [comment]
Hi,
Last snapshot use emoji in markdown

**Comment by clorichel** [comment]
Thank you very much for your feedback !

Have you got a download link for the latest snapshot, or any info on how to generate the `sonar-gitlab-plugin-latest.jar` ? For sure, you'll understand I'm not a Java boy, so if it's over complicated, please feel free to NOT learn me "how to Java" 😂

**Comment by johnou** [comment]
@clorichel 

```
git clone https://github.com/gabrie-allaigre/sonar-gitlab-plugin.git
cd sonar-gitlab-plugin
mvn clean package
```

you should then find a snapshot jar in the target directory.
