### ISSUE TITLE
Possibility to define a coverage gate

### ISSUE THREAD

**Issue by AlexSchuetz** [gabrie-allaigre/sonar-gitlab-plugin#50]
In addition to define gates on issue types, it would be nice to also be able to define a gate for coverage on new code.

Is this possible at all with preview analysis on sonarQube?

**Comment by gabrie-allaigre** [comment]
Hi,
No, SonarQube preview get only new issue

**Comment by AlexSchuetz** [comment]
Ok. I also read that coverage is only computed in full analysis.
