### ISSUE TITLE
External build status always failing, despite all sonar builds end successfully.

### ISSUE THREAD

**Issue by elboletaire** [gabrie-allaigre/sonar-gitlab-plugin#51]
**Gitlab version:**  9.3.6
**Gitlab sonar plugin version:** 2.1.0-beta (updated today from 2.0.0, to see if that fix the issue, but it's not the case).

Since we've updated gitlab to 9.3.X (I'm not sure in which exact version it started failing) external builds always fail, despite all builds build successfully.

In fact, it has been always a bit weird how this plugin manages the jobs in the pipelines view. In our case, we have 4 jobs in our pipeline, two of them are related to sonarqube (one for printing the issues in gitlab, the other to inform to sonarqube). Here's our actual `.gitlab-ci.yml` file:

<details>
<summary>Click to show contents of <code>.gitlab-ci.yml</code></summary>

~~~yaml
stages:
- test
- analysis

sonarqube:
  image: ciricihq/gitlab-sonar-scanner
  stage: analysis
  dependencies:
  - test
  variables:
    SONAR_URL: "http://OUR_SONAR_URL(hidden)"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONAR_ANALYSIS_MODE: "issues"
    SONAR_PROJECT_KEY: org.cirici.sonar:metropolitan-2015
  script:
  - /usr/bin/sonar-scanner-run.sh

sonarqube-reports:
  stage: analysis
  dependencies:
  - test
  only:
  - master
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: "http://OUR_SONAR_URL(hidden)"
    SONAR_PROJECT_VERSION: "$CI_BUILD_ID"
    SONAR_PROJECT_KEY: org.cirici.sonar:metropolitan-2015
  script:
  - /usr/bin/sonar-scanner-run.sh

test:
  image: ciricihq/php:7.0-seasoned
  stage: test
  artifacts:
    untracked: false
    when: on_success
    expire_in: 20min
    paths:
    - build/
  cache:
    paths:
    - vendor
  before_script:
  - ssh-keyscan -H gitlab.cirici.com > ~/.ssh/known_hosts
  - phpdismod xdebug
  - composer self-update
  - composer --no-interaction --prefer-dist install
  - yarn --only=production
  - phpenmod xdebug
  - bower install --allow-root
  - gulp
  script:
  - ./vendor/bin/phpunit --coverage-text --colors=never

casperjs:
  image: node:boron
  stage: test
  only:
  - master
  before_script:
  - yarn --production
  - yarn global add phantomjs casperjs
  script:
  - casperjs test tests/Casper/{desktop,mobile} --includes=tests/Casper/includes.js
~~~
</details>

<br />

The plugin always hides the pipelines, and creates a new one under `External` breaking the pipeline graph:

![imatge](https://user-images.githubusercontent.com/153305/28265769-bd8463ec-6af1-11e7-8e88-23d866085817.png)

Note that we have two jobs in the `Analysis` pipeline, but it shows it empty. If we check under the `Jobs` section, we can see that the `Analysis` job actually worked:

![imatge](https://user-images.githubusercontent.com/153305/28265884-46b3ad58-6af2-11e7-8ff7-6ac01d6ec4e2.png)

But the `external` sonarqube failed, without any kind of report:

![imatge](https://user-images.githubusercontent.com/153305/28265890-55b87432-6af2-11e7-92a6-5de9a0057016.png)

So... what's going on here? How can we debug this? I'm currently removing all the sonarqube stages from my gitlab-ci in order to get my builds "working" again (I cannot deploy if these steps don't work).

**Comment by gabrie-allaigre** [comment]
Hi,
Please, get log for Sonarqube analysis.
Thanks

**Comment by elboletaire** [comment]
@gtrias can you paste them here please? 😃

**Comment by gtrias** [comment]
One of the problems with this issue is the impossibility to see the sonarqube logs.

I'll try to get the logs once are running, maybe that way I'll be able to see them..

**Comment by gtrias** [comment]
Ok, I was be able to see the logs. For anyone with the same weird issue you has to click in the Pipelines -> Jobs tab.

Here you are @gabrie-allaigre :

```
[0KRunning with gitlab-ci-multi-runner 9.3.0 (3df822b)
  on metro-2015 (327470d7)
[0;m[0KUsing Docker executor with image ciricihq/gitlab-sonar-scanner ...
[0;m[0KUsing docker image sha256:b0f312352f837b6dab11b9136699dcac64daf43fa48c45844c7c0a952db7e6c3 for predefined container...
[0;m[0KPulling docker image ciricihq/gitlab-sonar-scanner ...
[0;m[0KUsing docker image ciricihq/gitlab-sonar-scanner ID=sha256:21bc90cb79c08ba14237b5bf5b6039ae37454c6eb2ff0149058ac9e085f2a2b9 for build container...
[0;mRunning on runner-327470d7-project-144-concurrent-0 via caprica...
[32;1mFetching changes...[0;m
Removing build/
Removing config/app.php
Removing node_modules/
Removing tmp/cache/models/
Removing tmp/cache/persistent/myapp_cake_core_translations__admin_l_t_e_es__e_s
Removing tmp/cache/persistent/myapp_cake_core_translations_cake_es__e_s
Removing tmp/cache/persistent/myapp_cake_core_translations_default_es__e_s
Removing tmp/cache/persistent/myapp_cake_core_translations_tools_es__e_s
Removing tmp/mini_asset_build_time
Removing vendor/albertofem/
Removing vendor/alchemy/
Removing vendor/aura/
Removing vendor/autoload.php
Removing vendor/bin/
Removing vendor/cakephp-plugins.php
Removing vendor/cakephp/
Removing vendor/ciricihq/
Removing vendor/club-metropolitan/
Removing vendor/cms/
Removing vendor/composer/
Removing vendor/dakota/
Removing vendor/dereuromark/
Removing vendor/dnoegel/
Removing vendor/doctrine/
Removing vendor/elboletaire/
Removing vendor/filp/
Removing vendor/friendsofcake/
Removing vendor/gourmet/
Removing vendor/guzzlehttp/
Removing vendor/html2text/
Removing vendor/jakub-onderka/
Removing vendor/jdorn/
Removing vendor/jeremyharris/
Removing vendor/justinrainbow/
Removing vendor/kevinlebrun/
Removing vendor/knplabs/
Removing vendor/league/
Removing vendor/markstory/
Removing vendor/michelf/
Removing vendor/mobiledetect/
Removing vendor/muffin/
Removing vendor/mustache/
Removing vendor/myclabs/
Removing vendor/nikic/
Removing vendor/opencomponents/
Removing vendor/oyejorge/
Removing vendor/pattern-lab/
Removing vendor/phpdocumentor/
Removing vendor/phpoffice/
Removing vendor/phpspec/
Removing vendor/phpunit/
Removing vendor/psr/
Removing vendor/psy/
Removing vendor/robmorgan/
Removing vendor/sebastian/
Removing vendor/seld/
Removing vendor/shudrum/
Removing vendor/squizlabs/
Removing vendor/symfony/
Removing vendor/tedivm/
Removing vendor/webmozart/
Removing vendor/wrench/
Removing vendor/xety/
Removing vendor/zendframework/
Removing webroot/js/dist/controls.png
Removing webroot/js/dist/infobubble.js
Removing webroot/js/dist/jquery.parseDataAttributes.js
Removing webroot/js/dist/lightslider.css
Removing webroot/js/dist/lightslider.js
Removing webroot/js/dist/masonry.pkgd.js
Removing webroot/js/dist/signature_pad.js
Removing webroot/vendor/
Removing yarn.lock
HEAD is now at 1b69b72 refs #106 Moved to beforeSave() method the item joinData saving
[32;1mChecking out 1b69b72e as b/fix-spreadsheets-issues-106...[0;m
[32;1mSkipping Git submodules setup[0;m
[32;1mDownloading artifacts for test (19151)...[0;m
Downloading artifacts from coordinator... ok      [0;m  id[0;m=19151 responseStatus[0;m=200 OK token[0;m=kRPK8V8z
[32;1m$ /usr/bin/sonar-scanner-run.sh[0;m
INFO: Scanner configuration file: /sonar-scanner-2.8/conf/sonar-scanner.properties
INFO: Project root configuration file: /builds/club-metropolitan/metropolitan-web-2015/sonar-project.properties
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_131 Oracle Corporation (64-bit)
INFO: Linux 3.16.0-4-amd64 amd64
INFO: User cache: /root/.sonar/cache
INFO: Load global repositories
INFO: Load global repositories (done) | time=63ms
INFO: User cache: /root/.sonar/cache
INFO: Exclude plugins: devcockpit, ldap, authgithub, authbitbucket, pdfreport, authaad, googleanalytics, governance
INFO: Load plugins index
INFO: Load plugins index (done) | time=2ms
INFO: Download sonar-css-plugin-3.1.jar
INFO: Download sonar-github-plugin-1.4.1.822.jar
INFO: Download sonar-python-plugin-1.8.0.1496.jar
INFO: Download sonar-android-plugin-1.1.jar
INFO: Download sonar-scm-svn-plugin-1.4.0.522.jar
INFO: Download sonar-javascript-plugin-3.1.1.5128.jar
INFO: Download sonar-csharp-plugin-6.1.0.2359.jar
INFO: Download sonar-java-plugin-4.11.0.10660.jar
INFO: Download sonar-web-plugin-2.5.0.476.jar
INFO: Download sonar-scm-git-plugin-1.2.jar
INFO: Download sonar-php-plugin-2.10.0.2087.jar
INFO: Download sonar-gitlab-plugin-2.0.1.jar
INFO: Download qualinsight-sonarqube-badges-3.0.1.jar
INFO: SonarQube server 6.2
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=64ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=1785ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=14ms
INFO: Load active rules
INFO: Load active rules (done) | time=177ms
INFO: Issues mode
INFO: Scanning only changed files
INFO: -------------  Scan org.cirici.sonar:metropolitan-2015
INFO: Language is forced to php
INFO: Load server rules
INFO: Load server rules (done) | time=44ms
INFO: Base dir: /builds/club-metropolitan/metropolitan-web-2015
INFO: Working dir: /builds/club-metropolitan/metropolitan-web-2015/.sonar
INFO: Source paths: config, plugins, src
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
INFO: Excluded sources: 
INFO:   plugins/**/tests/**
INFO:   src/Console/Installer.php
INFO:   plugins/**/config/**
INFO: 529 files indexed
INFO: 85 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for php: PSR-2
INFO: Sensor Embedded CSS Analyzer Sensor
INFO: 0 source files to be analyzed
INFO: Sensor Embedded CSS Analyzer Sensor (done) | time=28ms
INFO: Sensor C# Unit Test Results Import
INFO: 0/0 source files have been analyzed
INFO: Sensor C# Unit Test Results Import (done) | time=0ms
INFO: Sensor SonarJavaXmlFileSensor
INFO: Sensor SonarJavaXmlFileSensor (done) | time=1ms
INFO: Sensor PHP sensor
INFO: 293 source files to be analyzed
INFO: 293/293 source files have been analyzed
INFO: No PHPUnit test report provided (see 'sonar.php.tests.reportPath' property)
WARN: sonar.php.coverage.reportPath is deprecated as of SonarQube 6.2. Please consider using sonar.php.coverage.reportPaths
WARN: sonar.php.coverage.itReportPath is deprecated as of SonarQube 6.2. Please consider using sonar.php.coverage.reportPaths
WARN: sonar.php.coverage.overallReportPath is deprecated as of SonarQube 6.2. Please consider using sonar.php.coverage.reportPaths
INFO: Analyzing PHPUnit unit test coverage report: build/coverage.xml
WARN: Could not resolve 93 file paths in coverage.xml, first unresolved path: /builds/club-metropolitan/metropolitan-web-2015/plugins/FeesClient/src/Controller/AppController.php
INFO: Analyzing PHPUnit integration test coverage report: build/coverage.xml
WARN: Could not resolve 93 file paths in coverage.xml, first unresolved path: /builds/club-metropolitan/metropolitan-web-2015/plugins/FeesClient/src/Controller/AppController.php
INFO: Analyzing PHPUnit overall coverage report: build/coverage.xml
WARN: Could not resolve 93 file paths in coverage.xml, first unresolved path: /builds/club-metropolitan/metropolitan-web-2015/plugins/FeesClient/src/Controller/AppController.php
INFO: Sensor PHP sensor (done) | time=3795ms
INFO: Sensor Analyzer for "php.ini" files
INFO: Sensor Analyzer for "php.ini" files (done) | time=2ms
INFO: Load server issues
INFO: Load server issues (done) | time=42ms
INFO: Performing issue tracking
INFO: 568/568 components tracked
WARN: Console report is deprecated. Use SonarLint CLI to have local reports of issues
INFO: 

-------------  Issues Report  -------------

        +9 issues

        +3 critical
        +3 major
        +2 minor
        +1 info

-------------------------------------------


INFO: ANALYSIS SUCCESSFUL
INFO: Executing post-job GitLab Commit Issue Publisher
INFO: Report status=failed, desc=SonarQube reported 9 issues, with 3 critical (fail) and 3 major and 2 minor and 1 info
INFO: Task total time: 8.113 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 10.896s
INFO: Final Memory: 63M/1011M
INFO: ------------------------------------------------------------------------
[32;1mJob succeeded
[0;m
```

**Comment by gabrie-allaigre** [comment]
Thanks,
By default, when critical>0 or blocker > 0, build failed.
```
Report status=failed, desc=SonarQube reported 9 issues, with 3 critical (fail) and 3 major and 2 minor and 1 info
```

Option `sonar.gitlab.failure_notification_mode` Notification is in current build (exit-code) or in commit status (commit-status) (default commit-status)

`commit-status` add external job in gitlab pipeline.

**Comment by hbanafal** [comment]
@gabrie-allaigre I am using this command : - /usr/local/sonar-runner/bin/sonar-runner -Dsonar.ts.tslint.path=/usr/local/bin/tslint -Dsonar.ts.tslint.configPath=/tslint.json -Dsonar.projectName=$CI_PROJECT_PATH -Dsonar.projectKey=$CI_PROJECT_NAME:$CI_PROJECT_ID -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.login=$SONAR_LOGIN

and sonar.gitlab.failure_notification_mode is set to "exit-code". Now what is happening Quality Gate Failed
since previous version
24
New Vulnerabilities
> 0
since previous version
1,107
New Bugs
> 0
 but gitlab build is still passing, I ave added external to my stages also but still build is passing and the code is deployed. Can you please tell me what i am missing so that if Quality gate fails, then build should also failed.

**Comment by gabrie-allaigre** [comment]
Hi,
What is analyse mode ?

**Comment by hbanafal** [comment]
@gabrie-allaigre I have not set any analyse mode. I have used the above command. Which mode i need to set ?

**Comment by gabrie-allaigre** [comment]
Yes preview mode

**Comment by hbanafal** [comment]
@gabrie-allaigre I have tried with this preview mode and it passed saying that there is no new issues but there are issue. But it is comparing with last found issues. I am facing another problem whenever there is any issue with commit build failed but if developer again make a commit it got passed and the code is merged with the issues committed in last commit. How to resolve this ?

**Comment by gabrie-allaigre** [comment]
Hello,
The sonarqube preview mode compares the last full scan with the new code.
In my projects, the complete analysis is done on the Master.
In feature branch, use preview mode only.

**Comment by hbanafal** [comment]
@gabrie-allaigre This is the command am using for feature branch 
- /usr/local/sonar-runner/bin/sonar-runner -Dsonar.issuesReport.console.enable=true -Dsonar.projectName=$CI_PROJECT_PATH -Dsonar.projectKey=$CI_PROJECT_NAME:$CI_PROJECT_ID -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.analysis.mode=preview -Dsonar.gitlab.ping_user=true -Dsonar.gitlab.only_issue_from_commit_file=true -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.login=$SONAR_LOGIN

And this is the command for master  branch for full scan : 
/usr/local/sonar-runner/bin/sonar-runner -Dsonar.issuesReport.console.enable=true -Dsonar.analysis.mode=preview -Dsonar.projectName=$CI_PROJECT_PATH -Dsonar.projectKey=$CI_PROJECT_NAME:$CI_PROJECT_ID -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.login=$SONAR_LOGIN

Is this configuration correct?

**Comment by gabrie-allaigre** [comment]
No, Full scan not use preview mode and not set plugin.
```
/usr/local/sonar-runner/bin/sonar-runner -Dsonar.projectName=$CI_PROJECT_PATH -Dsonar.projectKey=$CI_PROJECT_NAME:$CI_PROJECT_ID -Dsonar.projectVersion=1.0 -Dsonar.sources=.  -Dsonar.login=$SONAR_LOGIN
```

**Comment by hbanafal** [comment]
@gabrie-allaigre Thanks a lot for your help and quick replies. I have just one more doubt lets take feature branch analysis in which i am analysing only committed files. And suppose there is a critical bug in commit file and the build failed and deployment of buggy code failed. Now the developer made another commit in any file by just putting a space. Now again the analysis started and this time it has passed as there was no critical issue in this committed file and the code got deployed to server with the previous buggy code as well. I want to know if there is any solution to this problem so that we can resolve this loop hole. Thanks in advance :)

**Comment by gabrie-allaigre** [comment]
Change set `-Dsonar.gitlab.only_issue_from_commit_file=false` or remove default is false

**Comment by hbanafal** [comment]
But then it will analyse complete project and i am not planning to fix old issues. I just want that is there any parameter which we can define in this case that the code in last 5 commits or no. of commits will be analysed only in that commit. @gabrie-allaigre It would  be grateful if you suggest something in this case.

**Comment by gabrie-allaigre** [comment]
Sorry, I'm repeat
The sonarqube preview mode compares the last full scan with the new code.
And get only new issues, not old.

Example:
Last full scan is commit 1 (get 100 issues)
Feature branche create 3 commits.
Preview mode get only new issues (get 10 issues) since commit 1

**Comment by gabrie-allaigre** [comment]
Yes, it's good

**Comment by hbanafal** [comment]
@gabrie-allaigre Thanks a lot for your help. Your help made my life easy :)

**Comment by elboletaire** [comment]
Ok thanks @gabrie-allaigre. Setting `sonar.gitlab.failure_notification_mode` to `exit-mode` fixed the issue.

**Comment by gentunian** [comment]
@gabrie-allaigre is there a way to configure blocker and critical issues count for external job not to fail when using `sonar.gitlab.failure_notification_mode=commit-status` ? Or is it possible to adjust this to the quality gate configured? This way, the external job won't fail when your quality gate isn't failing.
