### ISSUE TITLE
Can this plugin support Gradle Project

### ISSUE THREAD

**Issue by xuhengfei** [gabrie-allaigre/sonar-gitlab-plugin#57]
Can this plugin support Gradle Project?

I am use gradle project ,and I hope to use this plugin

**Comment by gabrie-allaigre** [comment]
Yes, you can use gradle.

**Comment by chyu01** [comment]
@gabrie-allaigre I want to use in gradle project, do you have some example ?  thanks.

**Comment by gabrie-allaigre** [comment]
Hi,
I use gradle with android project.

build.gradle
``` gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'me.tatarka:gradle-retrolambda:3.6.0'
        classpath 'org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.3' // <- Add
    }
}
..
```

Add
``` gradle
apply plugin: "org.sonarqube"
```

And in .gitlab-ci.yml

``` yml
./gradlew sonarqube -Dsonar.host.url=... -Dsonar.login=...
...
./gradlew sonarqube -Dsonar.host.url=... -Dsonar.login=... -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME -Dsonar.gitab.project_id=$CI_PROJECT_ID
```

**Comment by dzonekl** [comment]
Hi, I am [struggling](https://stackoverflow.com/questions/49879630/configuring-the-sonarqube-gitlab-plugin-preview-mode) with gradle and the gitlab plugin for Sonar. 
What could it be?

**Comment by gabrie-allaigre** [comment]
@dzonekl What version plugin ?

**Comment by gabrie-allaigre** [comment]
Try `-Dsonar.gitlab.failure_notification_mode=exit-code`

**Comment by dzonekl** [comment]
Hi, Plugin is: 2.1.0 installed

**Comment by dzonekl** [comment]
I tried with =exit-code, now I don't see the external job, but no comments in the Merge Request Either. 
Also, I just noticed in the README you use ```-Dsonar.gitlab.project_id=$CI_PROJECT_PATH```, but here you use $CI_PROJECT_ID. Does that make a difference? And am I supposed to see a background task in Sonar when doing analysis?

**Comment by gabrie-allaigre** [comment]
`-Dsonar.gitlab.project_id` accept $CI_PROJECT_PATH or $CI_PROJECT_ID. It's unique identifier for project
