### ISSUE TITLE
Pipeline blocked on sonar project builder

### ISSUE THREAD

**Issue by naerion89** [gabrie-allaigre/sonar-gitlab-plugin#58]
Bonjour,

J'essaie de configurer le plugin sonar-gitlab-plugin avec gitlab.com  (V9.5.0-rc4-ee) et sonarqube (6.5).
J'ai installé le plugin en version 2.0.1 dans sonar et j'ai configuré mon token dans sonar.

J'effectue la commande suivante : 
mvn --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.1:sonar -Dsonar.host.url=https://naerion-sonarqube.sloppy.zone:443 -Pcheck -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID

Voici la sortie de maven : 

19815 [INFO] 
19815 [INFO] --- jacoco-maven-plugin:0.7.9:report (post-unit-test) @ sample-java ---
19929 [INFO] Loading execution data file /builds/naerion/sample-java/target/jacoco.exec
20060 [INFO] Analyzed bundle 'sample-java' with 3 classes
20248 [INFO] 
20248 [INFO] --- maven-war-plugin:3.1.0:war (default-war) @ sample-java ---
21058 [INFO] Packaging webapp
21061 [INFO] Assembling webapp [sample-java] in [/builds/naerion/sample-java/target/sample-java-0.0.1-SNAPSHOT]
21072 [INFO] Processing war project
21180 [INFO] Webapp assembled in [119 msecs]
21239 [INFO] Building war: /builds/naerion/sample-java/target/sample-java-0.0.1-SNAPSHOT.war
22078 [INFO] 
22078 [INFO] ------------------------------------------------------------------------
22083 [INFO] Building sample-java 0.0.1-SNAPSHOT
22083 [INFO] ------------------------------------------------------------------------
22111 [INFO] 
22112 [INFO] --- sonar-maven-plugin:3.0.1:sonar (default-cli) @ sample-java ---
22931 [INFO] User cache: /root/.sonar/cache
26456 [INFO] Load global settings
27041 [INFO] Load global settings (done) | time=590ms
27067 [INFO] User cache: /root/.sonar/cache
27100 [INFO] Exclude plugins: devcockpit, ldap, authgithub, authbitbucket, pdfreport, authaad, googleanalytics, governance
27368 [INFO] Load plugins index
27466 [INFO] Load plugins index (done) | time=98ms
27475 [INFO] Download sonar-python-plugin-1.8.0.1496.jar
28488 [INFO] Download sonar-csharp-plugin-5.10.1.1411.jar
29332 [INFO] Download sonar-java-plugin-4.12.0.11033.jar
30122 [INFO] Download sonar-scm-git-plugin-1.2.jar
30425 [INFO] Download sonar-flex-plugin-2.3.jar
30618 [INFO] Download sonar-xml-plugin-1.4.3.1027.jar
31330 [INFO] Download sonar-php-plugin-2.10.0.2087.jar
31588 [INFO] Download sonar-gitlab-plugin-2.0.1.jar
31832 [INFO] Download sonar-scm-svn-plugin-1.5.0.715.jar
32290 [INFO] Download sonar-javascript-plugin-3.1.1.5128.jar
33008 [INFO] SonarQube version: 6.5.0
34646 [INFO] Default locale: "en", source code encoding: "UTF-8" (analysis is platform dependent)
35303 [INFO] Process project properties
35318 [INFO] Load project repositories
35686 [WARNING] Project doesn't exist on the server. All issues will be marked as 'new'.
35686 [INFO] Load project repositories (done) | time=368ms
35691 [INFO] Execute project builders

Le pipeline reste au statut pending. Je n'ai pas d'autres informations.

L'analyse sonar sans activer le plugin gitlab fonctionne parfaitement.

Voici l'url de sonar : https://naerion-sonarqube.sloppy.zone
Voici l'url du project gitlab : https://gitlab.com/naerion/sample-java

Pouvez-vous m'aider à résoudre ce problème ?
Cordialement,

**Comment by naerion89** [comment]
J'ai testé avec sonarqube 6.5 et gitlab 9.3.8-ee.
Vu qu'en version 9.5, gitlab déprécie l'api v3, j'ai essayé avec le plugin en beta et l'api v4 mais ca ne fonctionne pas.

**Comment by gabrie-allaigre** [comment]
Bonjour,
Vous utilisez bien GitLab-CI ?
Avez vous le log sonar au complet ?

Merci

**Comment by naerion89** [comment]
Bonjour,

Oui, j'utilise bien gitlab-ci depuis gitlab-com. En débug, il n'y a aucun
log dans sonar.
Par contre, il y a des mises à jour sur gitlab-com pour passer en gitlab
9.5 (api v3 déprécié)


Le 21 août 2017 10:36 AM, "Gabriel Allaigre" <notifications@github.com> a
écrit :

Bonjour,
Vous utilisez bien GitLab-CI ?
Avez vous le log sonar au complet ?

Merci

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/58#issuecomment-323681959>,
or mute the thread

**Comment by gabrie-allaigre** [comment]
Désolé, j'ai pas encore testé avec la 9.5 (elle n'est pas encore sortie et j'attends souvent 1 mois avant de faire la maj)
Est ce qu'il avait le problème avec la 9.4 ?

**Comment by naerion89** [comment]
Le problème a été corrigé. Çà marche à nouveau sur gitlab.com 9.5.0-rc8-ee
Je pense qu'il s'agit de régression du au développement de la version 9.5.

Mon issue peut donc être fermé.

Merci pour ton aide.

**Comment by gabrie-allaigre** [comment]
ok merci du retour.
Normalement la version avec api v4 fonctionne je l'utilise depuis la 9.0
Apres comme je te dis j'attends souvent avant de mettre à jour GitLab, car il y a toujours 4 à 5 updates
