### ISSUE TITLE
Does preview mode and Analysis mode with same rule

### ISSUE THREAD

**Issue by xuhengfei** [gabrie-allaigre/sonar-gitlab-plugin#61]
In feature branch,when I push, it will trigger sonar scan with preview mode.  
And than comment with no issues.

But in develop branch, I run with analysis mode, at sonar web site,it has a lot of issues.

Why the result is different in two mode?

**Comment by gabrie-allaigre** [comment]
Hi,
Plugin show only new issue between last analysis in sonar and feature branch.

**Comment by xuhengfei** [comment]
how to define last analysis?
last preview mode analysis is avaiable?
last full analysys mode is avaiable?
last analysis ignore different branch?

And how can I force full analysis in preview mode?

My project is old and have lots of issues.
I want plugin to comment all issues on gitlab,then developer need to fix issues before Merge Request.
What can I do ?

**Comment by gabrie-allaigre** [comment]
Plugin display new issue only, between last full analyse and current preview analyse.

**Comment by gabrie-allaigre** [comment]
I can add option to show all issues. I test if it works

**Comment by gabrie-allaigre** [comment]
Hi,
I added a option to show all issues
`-Dsonar.gitlab.all_issues=true`

Use 2.1.0-beta2

**Comment by xuhengfei** [comment]
thank you

**Comment by pkaramol** [comment]
@gabrie-allaigre is there any case the default setting was left to `true`?

We have been experiencing some issues with `-Dsonar.analysis.mode=preview` that behaves as full analysis, **unless* we set `-Dsonar.gitlab.all_issues=false`
