### ISSUE TITLE
api incompability

### ISSUE THREAD

**Issue by nospor** [gabrie-allaigre/sonar-gitlab-plugin#63]
Hi, I have SonarQube v6.5
I've installed sonar gitlab plugin v2.0.1
When I run command in gitlab-ci:
mvn --batch-mode verify sonar:sonar -Dsonar.host.url=URL_TO_MY_SONARQUBE

I have errors:
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project data-service: Execution default-cli of goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar failed: Unable to load the mojo 'sonar' in the plugin 'org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/sonarsource/scanner/maven/SonarQubeMojo : Unsupported major.minor version 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:sonar-maven-plugin:3.3.0.603
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/org/sonarsource/scanner/maven/sonar-maven-plugin/3.3.0.603/sonar-maven-plugin-3.3.0.603.jar
[ERROR] urls[1] = file:/root/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.2/maven-dependency-tree-2.2.jar
[ERROR] urls[2] = file:/root/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[3] = file:/root/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[4] = file:/root/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[5] = file:/root/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[7] = file:/root/.m2/repository/org/sonarsource/scanner/api/sonar-scanner-api/2.9.0.887/sonar-scanner-api-2.9.0.887.jar
[ERROR] urls[8] = file:/root/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[9] = file:/root/.m2/repository/com/google/code/findbugs/jsr305/2.0.3/jsr305-2.0.3.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

Should I additionally install something more?

**Comment by gabrie-allaigre** [comment]
Hi,
Plugin use java 8.
What java version ?

**Comment by nospor** [comment]
Ah.... 1.7.0_151
Ok, I will try update server then and let you know

**Comment by nospor** [comment]
Ok, with java8 it runs. But it analyse only pom.xml file and nothing more.
My pom.xml looks like this:
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>mediatel</groupId>
    <artifactId>data-service</artifactId>
    <version>1</version>
</project>

My gitlab-ci.yml looks like this:
sonarqube:
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=URL
  stage: test

**Comment by nospor** [comment]
Ok, I've read a little about maven and now I have fixed pom.xml file

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.sonarqube</groupId>
    <artifactId>some id</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>some name</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sonar.sources>./src</sonar.sources>
        <sonar.language>php</sonar.language>
    </properties>
</project>
```
Now is fine, it do analysis in SonarQube. But it still does not comment in gitlab even if there is a lot of bugs.

This is actual gitlba-ci.yml
```
stages:
  - build

sonarqube:
  image: maven
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=URL
  stage: build
  only:
    - bug/40513

```

**Comment by nospor** [comment]
And is working fine now. I had small error :) Thx :)

**Comment by vishnudahatonde** [comment]
> 
> 
> Ok, with java8 it runs. But it analyse only pom.xml file and nothing more.
> My pom.xml looks like this:
> 
> ```
> <project>
>     <modelVersion>4.0.0</modelVersion>
>     <groupId>mediatel</groupId>
>     <artifactId>data-service</artifactId>
>     <version>1</version>
> </project>
> ```
> 
> My gitlab-ci.yml looks like this:
> 
> ```
> sonarqube:
>   script:
>     - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=URL
>   stage: test
> ```

Hi, How did you changed it to java 8?

**Comment by nospor** [comment]
I just used docker container with java8 for what I remember
