### ISSUE TITLE
Will there be a new release soon?

### ISSUE THREAD

**Issue by chinhodado** [gabrie-allaigre/sonar-gitlab-plugin#64]
Will there be a new release soon?

**Comment by gabrie-allaigre** [comment]
Hi,
the last release was made 4 days ago.
Want a new feature?

**Comment by chinhodado** [comment]
Oh, is it available in SonarQube update center yet?

The readme is still saying "The version 2.0.1 is directly in the SonarQube update center"

**Comment by gabrie-allaigre** [comment]
Yes, 2.1.0 is in sonarqube update center.
I change readme, Tkx

**Comment by chinhodado** [comment]
Awesome, thanks!
