### ISSUE TITLE
Add configuration to add only issues on changes lines in main comment

### ISSUE THREAD

**Issue by PeterOsudio** [gabrie-allaigre/sonar-gitlab-plugin#66]
I do not know if this is already suggested in the past. If so please link and close this ticket.

I noticed that the plugin makes a general comment with the number of issues and inline comments on the lines where the issue was found. Regarding the general comment, I would like to have the options to show only the issues that were introduced with the code change instead of all issues of the whole project.

Please let me know if this is possible.

**Comment by gabrie-allaigre** [comment]
Hi,
Yes add : sonar.gitlab.only_issue_from_commit_file=true or sonar.gitlab.only_issue_from_commit_line=true

**Comment by PeterOsudio** [comment]
Ah cool, will try that. Thanks!

**Comment by PeterOsudio** [comment]
It works as a charm. Closing this ticket
