### ISSUE TITLE
Link to source line is not correct

### ISSUE THREAD

**Issue by reaction1989** [gabrie-allaigre/sonar-gitlab-plugin#67]
The link to the Source Code line in Gitlab is Case Sensitive.

I have no clue why the first 2 segments of the path are in lower-case.

This is the wrong link
http://gitlab.intranet.de/xya/project/blob/bb55415c5b7bbcb3cfb3b5da3737c4ddaa7e12ca/source/project.api/Component/CustomerRepository.cs#L30

This is the right link
http://gitlab.intranet.de/xya/project/blob/bb55415c5b7bbcb3cfb3b5da3737c4ddaa7e12ca/source/project.Api/Component/CustomerRepository.cs#L30

**Comment by gabrie-allaigre** [comment]
Hi,
The file path is given by SonarQube. The plugin only adds the Gitlab prefix.

https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/master/src/main/java/com/talanlabs/sonar/plugins/gitlab/GitLabApiV4Wrapper.java#L263

In SonarQube browser, file is correct name ?

**Comment by reaction1989** [comment]
It was a wrong configuration on my build server.

**Comment by gabrie-allaigre** [comment]
Ok, thanks

**Comment by artificerpi** [comment]
added: the common mistake which make this problem occur is the incorrect value of `sonar.projectBaseDir`
