### ISSUE TITLE
Installation-Configuration of Plugin

### ISSUE THREAD

**Issue by pmsudhi** [gabrie-allaigre/sonar-gitlab-plugin#7]
Hi,
Facing some issue regarding configuration of plugin. below the scenario.

**Environment:** 
1) Gitlab Running on Ubuntu 11.0
2) Sonarcube Running on windows 7
3) GitLab runner running on Windows 7
**Installation:**
1)Downloaded and added plugin to  SonarCube
2)From administration, added gitlab URL and User token
3) From project settings added Project URL
4) On the machine where CI runner is running installed and configured Maven
5) in the ci yaml file added a step for code analysis with 
`call mvn --batch-mode verify sonar:sonar -Dsonar.host.url=http://webbuild13:9000 -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME`

While running the CI, the build step fails with error MVN is not recognised command. but when i run mvn -v on command prompt where CI runner is installed it is giving correct output.

while i run the command directly on command prompt,

`mvn --batch-mode verify sonar:sonar -Dsonar.host.url=http://webbuild13:9000 -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=02e5fe46c932cafc437f939767bd91fbf0df67f8 -Dsonar.gitlab.ref_name=Sprint3`

i am getting error as attached
[mavenerror.txt](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/565720/mavenerror.txt)

The project I am trying to build/analysis is a c# project.
`

**Comment by gabrie-allaigre** [comment]
Hi, sorry but, Maven is for Java project.
For C# project use SonarCube Scanner http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

**Comment by pmsudhi** [comment]
Hi, Thanks for the clarification. Now configured SonarCube Scanner for my project but receiving the error as attached. can you please help me to figure this out

[test.txt](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/566130/test.txt)

**Comment by pmsudhi** [comment]
Hi, 
Thanks for the Clarification . managed to setup the sonarcube scanner and my task succeeds, but can't see the comments against commits. i also noticed that in my build pipeline though there is only 3 stages, i can see a 4th stage added automatically and marked as external, which is failed. attached is the log file from the console. in the log i can see the below messages
`15:08:34.724 DEBUG: Post-jobs : GitLab Commit Issue Publisher

15:08:34.724 INFO: Executing post-job GitLab Commit Issue Publisher

15:08:36.442 INFO: Task total time: 53.904 s

15:08:36.442 INFO: ------------------------------------------------------------------------

15:08:36.442 INFO: EXECUTION SUCCESS

15:08:36.442 INFO: ------------------------------------------------------------------------` 
[test.txt](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/566186/test.txt)

**Comment by gabrie-allaigre** [comment]
Hi,
External is fail because you have critical or blocker new issue.

**Comment by pmsudhi** [comment]
Oh .. Ok thanks. it is working fine now. Very nice effort and really usefull plugin @gabrie-allaigre . now it is time to spread the word 👍
