### ISSUE TITLE
Image url

### ISSUE THREAD

**Issue by legroen** [gabrie-allaigre/sonar-gitlab-plugin#70]
Hi,

Is it possible to control the url of the used images in the inline and global comment?

thx

**Comment by gabrie-allaigre** [comment]
Hi,
Yes, use template 
Inline : https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/master/templates/inline/default-image.md
Global : https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/master/templates/global/default-image.md
