### ISSUE TITLE
Do I need a GitLab runner?

### ISSUE THREAD

**Issue by flexaddicted** [gabrie-allaigre/sonar-gitlab-plugin#72]
Following the documentation in [README](https://gitlab.talanlabs.com/gabriel-allaigre/sonar-gitlab-plugin/blob/master/README.md), the `yml` file has a `script` section like the following:

```
 - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=XXX
```

In GitLab I do not have any runner in order to execute the specified `mvn` command. What's the best way to achieve it? Should I install a GitLab runner that provides a Maven configuration?
I cannot find it anywhere in the documentation presented above.

Thank you in advance.

**Comment by gabrie-allaigre** [comment]
Hi,
If runner is docker then use maven image
or if shell runner, install maven.

I'm use a runner with docker.

**Comment by flexaddicted** [comment]
@gabrie-allaigre Thank you for your reply.
