### ISSUE TITLE
Error when running 'sonarqube_preview'

### ISSUE THREAD

**Issue by alixwar** [gabrie-allaigre/sonar-gitlab-plugin#73]
I have added the 'sonarqube_preview' config from README to my CI build and I see this in the logs:

```
Checking out 7b887fb3 as experiment/the_branch_with_my_change...
Skipping Git submodules setup
$ git checkout origin/master
Previous HEAD position was 7b887fb3f4... Fixed tag
HEAD is now at 67d6c6a01b... Merge branch 'Some_other_branch' into 'master'
$ git merge $CI_BUILD_REF --no-commit --no-ff
merge: $CI_BUILD_REF - not something we can merge
ERROR: Job failed: exit status 1
```

My gitlab-ci conf file is exactly as in the README except that I hard-coded the URL so my sonar instance for -Dsonar.host.url

Any idea what could be wrong?

**Comment by alixwar** [comment]
Note: There is no merge conflict when I see the merge request in Gitlab

**Comment by gabrie-allaigre** [comment]
Hi,
Gitlab change variables name since 9.0
https://docs.gitlab.com/ce/ci/variables/#9-0-renaming
$CI_BUILD_REF -> $CI_COMMIT_SHA

**Comment by alixwar** [comment]
@gabrie-allaigre Thanks for the help but I'm actually running this on a Gitlab 8 server instance

**Comment by gabrie-allaigre** [comment]
what is the version of the runner?

**Comment by gabrie-allaigre** [comment]
what is the environment of the runner? linux? windows?

**Comment by alixwar** [comment]
> what is the version of the runner?

gitlab-ci-multi-runner 1.11.1

> what is the environment of the runner? linux? windows?

Windows

**Comment by gabrie-allaigre** [comment]
Ok, use `%CI_BUILD_REF%`

**Comment by gabrie-allaigre** [comment]
For environnement variable :
- Prefix $, is only for linux, mac, unix system
- For windows is %...%

**Comment by alixwar** [comment]
Thank you @gabrie-allaigre !
That was the problem
