### ISSUE TITLE
Maven build error "Unable found project for "

### ISSUE THREAD

**Issue by alixwar** [gabrie-allaigre/sonar-gitlab-plugin#74]
`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project root: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor: Unable found project for https://myserver.com/path/myproject Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 2]`

I'm getting this error and I'm trying to figure out what could be wrong. The user token should be correct (maps to a user with developer role in all projects on the server instance). I think the project ID should be okay?

According to the README:

> sonar.gitlab.project_id | Project ID in GitLab or internal id or namespace + name or namespace + path or url http or ssh url or url or web

**Comment by alixwar** [comment]
I found a possible solution: https://stackoverflow.com/questions/39559689/where-do-i-find-the-project-id-for-the-gitlab-api

Will check if this works...

**Comment by alixwar** [comment]
Same problem... Hmm

**Comment by gabrie-allaigre** [comment]
Hi,
In sonar call add -Dsonar.gitlab.project_id=%CI_PROJECT_PATH% for Windows

**Comment by alixwar** [comment]
Note: I've set the sonar.gitlab.user_token property in SonarQube. Will now try to set it explicitly in the gitlab ci config to see if helps

**Comment by alixwar** [comment]
Setting the token explicitly in the build config did not help

**Comment by gabrie-allaigre** [comment]
normally the error message should contain the project id
`throw new IllegalStateException("Unable found project for " + config.projectId() + " Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project");`
the problem may be the runner version. CI_PROJECT_PATH does not exist in version 1.11 ?
Try : -Dsonar.gitlab.project_id=namespace/projectName

**Comment by alixwar** [comment]
Thanks @gabrie-allaigre 

Your suggestion did improve on the error message a little. It now says:

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project root: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor: Unable found project for namespace/myproject Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 2]

**Comment by gabrie-allaigre** [comment]
do you have to replace namespace and projectname correctly with your project?

**Comment by alixwar** [comment]
Yeah, my project name is "myproject" and the namespace that the project belongs to is named "namespace" so I passed `sonar.gitlab.project_id=namespace/myproject`

**Comment by alixwar** [comment]
Maybe (hopefully) unrelated but I get some other errors before this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project webapp: Failed to copy file for artifact [com.mycompany:domain:jar:7.2-SNAPSHOT:compile]: C:\GitLab-Runner\builds\eb10224c\0\namespace\myproject\manager\domain\target\classes (Access is denied) -> [Help 2]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.1:copy-dependencies (copy-remote-tools-dependencies) on project simulator: Error copying artifact from C:\GitLab-Runner\builds\eb10224c\0\namespace\myproject\manager\domain\target\classes to C:\GitLab-Runner\builds\eb10224c\0\namespace\myproject\remote\simulator\target\lib\classes: C:\GitLab-Runner\builds\eb10224c\0\namespace\myproject\manager\domain\target\classes (Access is denied) -> [Help 2]
```

**Comment by gabrie-allaigre** [comment]
Hi,
user_token access to project ?

**Comment by alixwar** [comment]
Hi,
unfortunately it's not in Gitlab :-/
Is there something you would like to know about the config? I can find out

**Comment by gabrie-allaigre** [comment]
Sorry, I don't undestand.
the plugin needs a GitLab user who can access the project
`sonar.gitlab.user_token` is private token in GitLab.
User must have developer on project

**Comment by alixwar** [comment]
I completely misunderstood your question. Yes, the user_token references a user that has developer access to all projects on that Gitlab installation

**Comment by alixwar** [comment]
I will try with a newer version of the runner (1.9.5) and see if it helps

**Comment by alixwar** [comment]
I will try again building on a different machine with a different version of the gitlab runner. I'll know the result on Monday

**Comment by gabrie-allaigre** [comment]
Try to set `sonar.gitlab.url`

**Comment by alixwar** [comment]
My build failed unfortunately for other reasons. Will try explicitly settings properties as you suggested (even though they are set in SonarQube already)

**Comment by alixwar** [comment]
OK, another error message now. Maybe this is what caused the problems in the first place (cannot confirm this):

```
fatal: unable to access 'https://gitlab-ci-token:xxxxxx@mycompanyserver_address/namespace/myproject.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to mycompanyserver_address:443 
Checking out dcd2fc47 as experiment/sonarqube_gitlab...
fatal: reference is not a tree: dcd2fc4759941af3f6310c83ced722f1bbffa358
ERROR: Job failed: exit status 128
```

**Comment by alixwar** [comment]
When logging in using my CI user to Gitlab it turns out I did not have the privileges for that user that I expected. So I will retrack a bit and try the different suggestions in this ticket.

**Comment by alixwar** [comment]
Update: I have strong indications that my problem is the connection between the SonarQube instance and the Gitlab instance...

**Comment by alixwar** [comment]
It works now. I haven't really changed anything since it didn't work but there seems to be connectivity issues between the different servers. 

Thanks for your help @gabrie-allaigre

**Comment by gabrie-allaigre** [comment]
Ok good. Thanks
