### ISSUE TITLE
Unable to analyse and comment for private sonar projects

### ISSUE THREAD

**Issue by PeterOsudio** [gabrie-allaigre/sonar-gitlab-plugin#76]
Hi,

I don't know if this is a known issue. I searched the existing issues, but couldn't find anything similar, so I just decided to open an issue for it. Forgive my ignorance. 

We have the plugin working, but when changing a project in sonar to private, the MR analysis fails with a permission exception: 

```
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: You don't have the required permissions to access this project. Please contact your SonarQube administrator.
```

We enabled sonar analysis in the global permissions for 'everyone' but that didn't help. As the plugin in only aware of a usertoken and does not use a sonar account/user, we do not see how to give the right permissions, within a private project. 

Hopefully this is easily solvable, please point us in the right direction. 
Any help is appreciated.

Regards Peter

**Comment by gabrie-allaigre** [comment]
Hi,
sorry I use SonarQube with an authentication.
without the plugin the preview works?

**Comment by PeterOsudio** [comment]
We also use sonarqube with authentication. And it does work with non-private projects. 
I want to make the project private, but then above error occurs.

**Comment by gabrie-allaigre** [comment]
does user token sonarqube have access to the project?

**Comment by PeterOsudio** [comment]
The user token is not a real sonar-user right? So how do we give project permissions to the user token?

**Comment by PeterOsudio** [comment]
@gabrie-allaigre we still did not find a solution. Can you explain how to provide permissions for the usertoken?

**Comment by gabrie-allaigre** [comment]
Hi,
In sonarqube, go to project, 
In project menu -> Administration -> Permission
My project is private, my token is a user in sonar, name is GitLab-CI and permission is TalanLabs-users

![image](https://user-images.githubusercontent.com/14994297/32770530-511ef702-c920-11e7-8187-11bf1ee2fccc.png)

**Comment by PeterOsudio** [comment]
Thanks for the explaination. Our mistake was that we mixed gitlab and sonar tokens. After adding sonar.login=SONAR_TOKEN it works.

Thanks for your time!
