### ISSUE TITLE
Clearer docs for `only_issue_from_commit_file` and `only_issue_from_commit_line` options

### ISSUE THREAD

**Issue by Tzrlk** [gabrie-allaigre/sonar-gitlab-plugin#77]
At the moment, the documentation says "Show issue for commit line/file only (default false)", but my question is, what does that actually mean? Does it mean that it'll only create comments for issues on lines/files that have changed across the merge commit?

**Comment by gabrie-allaigre** [comment]
Hi,
Yes, plugin add comment only if line or file inside commit.

**Comment by Tzrlk** [comment]
Cheers.
