### ISSUE TITLE
Comment images are not aligned

### ISSUE THREAD

**Issue by jairbubbles** [gabrie-allaigre/sonar-gitlab-plugin#8]
With SonarQube 6.0 and GitLab plugin 1.7 I get this :
![2016-11-03 09_18_36-commented code for testing sonarqube d89ad6ef commits toolsquare _ gitla](https://cloud.githubusercontent.com/assets/15875066/19959366/86dff5a0-a1a6-11e6-8ab5-afb963f8aaaa.png)

Which looks different from your screenshots.

**Comment by johnou** [comment]
Looks better with emoji..

![sonarr](https://cloud.githubusercontent.com/assets/323497/23510249/0bdf243c-ff59-11e6-9de7-e132a73d6bd3.png)

@gabrie-allaigre should be ok to close this issue.
