### ISSUE TITLE
Question: How to disable comments on issues on unchanged lines?

### ISSUE THREAD

**Issue by alwa** [gabrie-allaigre/sonar-gitlab-plugin#81]
Hi,
I would like to disable getting these warnings:

> Note: The following issues were found on lines that were not modified in the commit. Because these issues can't be reported as line comments, they are summarized here:

Is there a configuration parameter to do so or should I remove this section from the Global template? If so, exactly which part should be removed?

**Comment by alwa** [comment]
It seems like setting `sonar.gitlab.disable_global_comment` to true would disable more than I want

**Comment by gabrie-allaigre** [comment]
Hi,
Use
sonar.gitlab.only_issue_from_commit_line -> Show issue for commit line only (default false)

**Comment by alixwar** [comment]
Ok, thanks!
