### ISSUE TITLE
Question: Gitlab user privileges for this plugin to work

### ISSUE THREAD

**Issue by alixwar** [gabrie-allaigre/sonar-gitlab-plugin#88]
Hi,
in the configuration you need to specify a user token for accessing the Gitlab project. Could you clarify which is the minimum role needed for this Gitlab user? I.e. is it "Guest", "Reporter" or "Developer"? 

I have some [idea](https://docs.gitlab.com/ee/user/permissions.html) but since I don't know what happens under-the-hood it would be good to have this clarified

Thanks
/ Alix

**Comment by gabrie-allaigre** [comment]
Hi,
If sonar.gitlab.failure_notification_mode is commit-status then role is Developer else Reporter.
Thanks

**Comment by mig-visiblee** [comment]
Hi Gabriel, and thanks much for this plugin!
we use 3.0.2 against latest GitLab CE (11.4) and SonarQube 6.7.1.
Our GitLab CI script says
```      mvn verify sonar:sonar $SONAR_MODE \
        -Dmaven.repo.local=$LOCAL_MVN_REPO $MAVEN_CLI_OPTS \
        -Dmaven.test.skip=true \
        -Dsonar.host.url=$SONAR_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.password=$SONAR_PASSWORD \
        -Dsonar.gitlab.api_version=v4 \
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
        -Dsonar.gitlab.url=$GITLAB_URL \
        -Dsonar.gitlab.user_token=$SONAR_GITLAB_TOKEN \
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME \
        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
```
`SONAR_GITLAB_TOKEN` refers to a user that has API access and is a Developer in the group in which our project is located, and we get this nonetheless:
```[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project backend: Insufficient privileges -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.5.0.1254:sonar (default-cli) on project backend: Insufficient privileges
```
The only thing I can think of would be that although our project path is `visiblee/java`, the plugin sees it as `backend`(which is the POM project name), but that quite does not fit with "insufficient privileged" as I would rather expect something like "non existent project". I did not dig into the code, but I thought I'd ask before I do so...

Thanks in advance,
Christophe.

**Comment by mig-visiblee** [comment]
Unless... We're in a branch and as I'm trying out the plugin before merging, I'm not using "preview" mode and perhaps the plugin is trying to decorate `master`, which is protected?
