### ISSUE TITLE
Get issues not related to new changes in branch

### ISSUE THREAD

**Issue by 0136** [gabrie-allaigre/sonar-gitlab-plugin#9]
I have problem when my master is ahead a couple of commits. For my branch I get issue which isn't related to my changes.

**Comment by johnou** [comment]
@0136 are you publishing the Sonar results when building master branch?

**Comment by 0136** [comment]
@johnou yep, of course. I'm trying to describe my problem by a diagram.

A -> B ->C - main branch
↳ X -> Y - feature branch

My CI server runs a sonar publish analysis on every main branch commits, for feature branch - only preview analysis. 

For feature branch analysis I get the issues from main branch for B and C commits.

**Comment by johnou** [comment]
Might see a pull request with a potential fix tomorrow https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/12#issuecomment-283757980

**Comment by 0136** [comment]
Any news?

**Comment by gabrie-allaigre** [comment]
Hi,
I try to understand your problem.
Normally SonarQube analyzed your master with B & C commit.
Your feature branch is offset relative to your master.
The operation of SonarQube is

master -> get All Issues (v1)
feature branch -> get All Issues (v2)

New issues are v2 - v1 = v3

**Comment by gabrie-allaigre** [comment]
If you want the only issues from commit use the variable sonar.gitlab.only_issue_from_commit_file=true

**Comment by gabrie-allaigre** [comment]
In my gitlab-ci, i merge feature branch with master before build

```bash
build_merge_job:
  stage: build
  except:
    - master
    - /^release-.*$/
    - tags
  script:
    - git checkout origin/master
    - git merge $CI_BUILD_REF --no-commit --no-ff
    - mvn --batch-mode ...
```

**Comment by 0136** [comment]
Hi, @gabrie-allaigre,
Thanks for your answers.

The idea with a merge branches is good, but think it's kinda workaround. If I set variable sonar.gitlab.only_issue_from_commit_file=true I'll get the issues only for last commit or for all files from all commits in branch?

**Comment by johnou** [comment]
@gabrie-allaigre that's the multi-hash feature you are working on, right?

**Comment by gabrie-allaigre** [comment]
@0136  If set variable sonar.gitlab.only_issue_from_commit_file=true, only for last commit

**Comment by 0136** [comment]
:disappointed:
