### ISSUE TITLE
Caused by: {"message":"401 Unauthorized"}   Need  advice 

### ISSUE THREAD

**Issue by gudge25** [gabrie-allaigre/sonar-gitlab-plugin#90]
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 13.051s
INFO: Final Memory: 46M/217M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder
ERROR: Caused by: Unable to perform GitLab WS operation
ERROR: Caused by: {"message":"401 Unauthorized"}
ERROR: Caused by: Server returned HTTP response code: 401 for URL: https://gitlab.com/api/v3/projects
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

during sonarcube  job 
thanks in advance

**Comment by gabrie-allaigre** [comment]
Hi,
Have you set USER_TOKEN in settings ?

**Comment by gudge25** [comment]
thanks
