### ISSUE TITLE
Only post Blocker and Critical issues (filter by severity)

### ISSUE THREAD

**Issue by jakub-bochenski** [gabrie-allaigre/sonar-gitlab-plugin#94]
We'd like to have a flow where all the issues are displayed in the developer's IDE, but on Gitlab only Blocker and Critical issues are posted.

We organize our rules so that the two most severe levels are must fix and the rest is considered advisory for the author.

We would like to avoid a situation when the MR is spamed by minor/info issues.

From what I've found there are separate thresholds for failing the build but I couldn't find any setting to filter comments by severity. 

This looks like a simple feature so I'd be willing to take a stab at PR given some guidance.

**Comment by gabrie-allaigre** [comment]
Hi,
I'm doing a big modification, I can add this feature. How would you like to configure it?

**Comment by jakub-bochenski** [comment]
I think we could do with just one variable, e.g. `sonar.gitlab.severity_treshold=[blocker|critical|major|minor|info]`

I prefer to keep the settings in `pom.xml` so "Variable" would be enough for me, but for sake of consistency with `sonar.gitlab.max_*_issues_gate` it should be a "Project, Variable"

**Comment by gabrie-allaigre** [comment]
Hi,
you can do it by modifying the templates.
If the template returns an empty string, it does not display a message.

For global

```injectedfreemarker
<#assign newIssueCount = issueCount() notReportedIssueCount = issueCount(false)>
<#assign hasInlineIssues = newIssueCount gt notReportedIssueCount extraIssuesTruncated = notReportedIssueCount gt maxGlobalIssues>
<#assign newIssuesBlocker = issueCount(BLOCKER) newIssuesCritical = issueCount(CRITICAL)>
<#if newIssuesBlocker gt 0 || newIssuesCritical gt 0>
SonarQube analysis reported ${newIssueCount} issue<#if newIssueCount gt 1>s</#if>
    <#assign newIssuesBlocker = issueCount(BLOCKER) newIssuesCritical = issueCount(CRITICAL) newIssuesMajor = issueCount(MAJOR) newIssuesMinor = issueCount(MINOR) newIssuesInfo = issueCount(INFO)>
    <#if newIssuesBlocker gt 0>
* ${emojiSeverity(BLOCKER)} ${newIssuesBlocker} blocker
    </#if>
    <#if newIssuesCritical gt 0>
* ${emojiSeverity(CRITICAL)} ${newIssuesCritical} critical
    </#if>
    <#if newIssuesMajor gt 0>
* ${emojiSeverity(MAJOR)} ${newIssuesMajor} major
    </#if>
    <#if newIssuesMinor gt 0>
* ${emojiSeverity(MINOR)} ${newIssuesMinor} minor
    </#if>
    <#if newIssuesInfo gt 0>
* ${emojiSeverity(INFO)} ${newIssuesInfo} info
    </#if>
    <#if !disableIssuesInline && hasInlineIssues>

Watch the comments in this conversation to review them.
    </#if>
    <#if notReportedIssueCount gt 0>
        <#if !disableIssuesInline>
            <#if hasInlineIssues || extraIssuesTruncated>
                <#if notReportedIssueCount <= maxGlobalIssues>

#### ${notReportedIssueCount} extra issue<#if notReportedIssueCount gt 1>s</#if>
                <#else>

#### Top ${maxGlobalIssues} extra issue<#if maxGlobalIssues gt 1>s</#if>
                </#if>
            </#if>

Note: The following issues were found on lines that were not modified in the commit. Because these issues can't be reported as line comments, they are summarized here:
        <#elseif extraIssuesTruncated>

#### Top ${maxGlobalIssues} issue<#if maxGlobalIssues gt 1>s</#if>
        </#if>

        <#assign reportedIssueCount = 0>
        <#list issues(false) as issue>
            <#if reportedIssueCount < maxGlobalIssues>
1. ${print(issue)}
            </#if>
            <#assign reportedIssueCount++>
        </#list>
        <#if notReportedIssueCount gt maxGlobalIssues>
* ... ${notReportedIssueCount-maxGlobalIssues} more
        </#if>
    </#if>
</#if>
```

For inline

```injectedfreemarker
<#assign newIssuesBlocker = issueCount(BLOCKER) newIssuesCritical = issueCount(CRITICAL)>
<#if newIssuesBlocker gt 0 || newIssuesCritical gt 0>
<#list issues() as issue>
<@p issue=issue/>
</#list>
</#if>
<#macro p issue>
${emojiSeverity(issue.severity)} ${issue.message} [:blue_book:](${issue.ruleLink})
</#macro>
```

**Comment by jakub-bochenski** [comment]
Great - thanks. Will test it tomorrow.

I still think having an explicit threshold setting might be a nice improvement (if only because it's easier to find)

**Comment by jakub-bochenski** [comment]
The inline comments are not posted, but the summary still is posted.
I'm not sure if this is a problem for me, but it seems weird given the `<#if newIssuesBlocker gt 0 || newIssuesCritical gt 0>` part.

![screenshot_20180118_123829](https://user-images.githubusercontent.com/2794994/35096547-dd923276-fc4c-11e7-8ad6-19421f0fe465.png)

**Comment by gabrie-allaigre** [comment]
it displays the message well because there are 2 blockers and 9 criticals.
In the sample template I gave it was only to display the message if there are critical and blockers
But if you do not want the list of majors, minors and info you have to change the template

Remove

```
 <#if newIssuesMajor gt 0>
* ${emojiSeverity(MAJOR)} ${newIssuesMajor} major
    </#if>
    <#if newIssuesMinor gt 0>
* ${emojiSeverity(MINOR)} ${newIssuesMinor} minor
    </#if>
    <#if newIssuesInfo gt 0>
* ${emojiSeverity(INFO)} ${newIssuesInfo} info
    </#if>
```

and we must also adapt the end

**Comment by jakub-bochenski** [comment]
Maybe this is some misunderstanding on my part.
I assumed `newIssuesBlocker` refers to the issues introduced in the MR (one that'd get inline comments).
I think the reported 2 blockers and 9 criticals are found in the touched files but are not new issues.

**Comment by jakub-bochenski** [comment]
@gabrie-allaigre turns out sonar was marking all the issues as "new".
The reason is described in #100

**Comment by jakub-bochenski** [comment]
For some reason the build started to break when using the custom inline template :(
```
19:09:29 [ERROR] [19:09:49.221] Failed to create template inline
19:09:29 freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
19:09:29 ==> issue.ruleLink  [in template "inline" at line 8, column 67]
19:09:29 
19:09:29 ----
19:09:29 Tip: It's the step after the last dot that caused this error, not those before it.
19:09:29 ----
19:09:29 Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
19:09:29 ----
19:09:29 
19:09:29 ----
19:09:29 FTL stack trace ("~" means nesting-related):
19:09:29 	- Failed at: ${issue.ruleLink}  [in template "inline" in macro "p" at line 8, column 65]
19:09:29 	- Reached through: @p issue=issue  [in template "inline" at line 4, column 1]
19:09:29 ----
```

Any idea what is the reason? When I remove the custom inline template the comments are posted

**Comment by jakub-bochenski** [comment]
for now I've removed the ` ${issue.ruleLink} ` part

**Comment by gabrie-allaigre** [comment]
Hi,
Sorry, `${issue.ruleLink}` is only for plugin version 3.0.0
Correct template for 2.1.0 is here https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/2.1.0/templates/inline/default.md

**Comment by jakub-bochenski** [comment]
FTR this is the template that works for 2.1
```
<#assign newIssuesBlocker = issueCount(BLOCKER) newIssuesCritical = issueCount(CRITICAL)>
<#if newIssuesBlocker gt 0 || newIssuesCritical gt 0>
<#list issues() as issue>
<@p issue=issue/>
</#list>
</#if>
<#macro p issue>
${emojiSeverity(issue.severity)} ${issue.message} [:blue_book:](${ruleLink(issue.ruleKey)})
</#macro>
```

**Comment by gabrie-allaigre** [comment]
Hi,
Version 3.0.0 add filter `sonar.gitlab.issue_filter`
