### ISSUE TITLE
sonar.gitlab.url missing port

### ISSUE THREAD

**Issue by evbo** [gabrie-allaigre/sonar-gitlab-plugin#99]
Hi,

I have set my `sonar.gitlab.url` correctly _with a port_ (8888) In SonarQube: Administration > GitLab > [GitLab url](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/blob/8623cfc0bfb990c0abc4e87b2c1be572020f50a5/src/main/java/com/talanlabs/sonar/plugins/gitlab/GitLabPlugin.java#L32)

However, the comments that are embedded in my merge request have links to the issues with the port (8888) missing. As such, all links are broken until I manually add the 8888 port back into them after clicking on them.

Is this a bug? How can I ensure the port is used for generating all links to my project source?

**Comment by gabrie-allaigre** [comment]
Hi,
I use web_url in project api

```
https://mygitlab:8888/api/v4/projects/:id
```

replace id by id project, found in settings project in gitlab
In json, I use field `web_url`

Have you correct url ?

Thanks

**Comment by evbo** [comment]
It turns out in order for this to work the `external_url` must have the port explicitly referenced in `/etc/gitlab/gitlab.rb`

I didn't originally have that set because I was accounting for it with:
```
##! **Override only if you use a reverse proxy**
##! Docs: https://docs.gitlab.com/omnibus/settings/nginx.html#setting-the-nginx-listen-port
nginx['listen_port'] = 8888
```

**Comment by gabrie-allaigre** [comment]
Thanks

**Comment by evbo** [comment]
Related to this issue with Comments is that gitlab "issues" also don't include the port. I am posting an issue separately for that here: https://gitlab.com/gitlab-org/gitlab-ce/issues/42608
